'use strict';
const assert = require('assert/strict');
const fs = require('fs');
const path = require('path');
const { chromium } = require('playwright');
const campanha = require('./public/login-campanha');
async function testarVisual(){
  const fim = Date.parse(campanha.PADRAO.campanhaFim);
  const salva = { ativo: true, bubbleTitulo: 'Outubro Rosa: cuidado que acolhe 🎀', bubbleTexto: 'Neste Outubro Rosa, o NoPulso se veste de carinho e esperança. Juntos na conscientização sobre o câncer de mama, acolhendo quem enfrenta essa jornada e quem caminha ao seu lado. 💗', fundoArquivo: 'desktop', fundoMobileArquivo: 'mobile' };
  assert.equal(campanha.efetiva(salva,fim-1).rosaAtiva,true);
  const encerrada = campanha.efetiva(salva,fim);
  assert.equal(encerrada.rosaAtiva,false);
  assert.equal(encerrada.fundoArquivo,null);
  assert.equal(encerrada.bubbleTitulo,'');
  assert.equal(salva.fundoArquivo,'desktop','Não apaga os arquivos salvos');
  assert.equal(campanha.efetiva(salva,Date.parse('2027-10-05T12:00:00-03:00')).rosaAtiva,false,'Não volta no ano seguinte');
  assert.equal(campanha.efetiva({...salva,campanhaRosa:false},fim).fundoArquivo,'desktop','Controle manual desativa encerramento');
  const browser = await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true});
  const pasta = path.join(__dirname,'public');
  const html = fs.readFileSync(path.join(pasta,'index.html'),'utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'');
  const painel = fs.readFileSync(path.join(pasta,'login-custom.html'),'utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'');
  const saida = path.join(__dirname,'../docs/varredura/login-outubro-rosa');
  fs.mkdirSync(saida,{recursive:true});
  try {
    for(const [w,h] of [[320,740],[390,844],[768,1024],[1262,994],[1366,768],[1920,1080],[2560,1440]]) {
      const page = await browser.newPage({viewport:{width:w,height:h}});
      await page.route('http://login.teste/**',async route => {
        const u = new URL(route.request().url());
        if(u.pathname === '/') return route.fulfill({contentType:'text/html',body:html});
        const arquivo = path.resolve(pasta,'.'+u.pathname);
        if(!arquivo.startsWith(pasta+path.sep) || !fs.existsSync(arquivo) || !fs.statSync(arquivo).isFile()) return route.fulfill({status:404});
        const ext = path.extname(arquivo);
        return route.fulfill({contentType:({'.js':'application/javascript','.svg':'image/svg+xml','.png':'image/png','.woff2':'font/woff2'})[ext]||'application/octet-stream',body:fs.readFileSync(arquivo)});
      });
      await page.goto('http://login.teste/');
      await page.addScriptTag({url:'http://login.teste/tema.js'});
      await page.addScriptTag({url:'http://login.teste/login-campanha.js'});
      await page.addScriptTag({url:'http://login.teste/login-campanha-ui.js'});
      await page.evaluate(c=>window.aplicarLoginCampanha(c),{...salva,servidorAgora:'2026-10-05T12:00:00-03:00'});
      await page.locator('#btn-biometria').evaluate(e=>e.classList.remove('hidden'));
      assert.equal(await page.locator('#auth-screen').evaluate(e=>getComputedStyle(e).backgroundPosition),'100% 100%');
      assert.equal(await page.locator('#auth-form .auth-marca>svg').isVisible(),false);
      assert.equal(await page.locator('.login-bubble b').evaluate(e=>getComputedStyle(e).fontSize),'16px');
      assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`Sem overflow em ${w}`);
      const campo = await page.locator('#auth-email').boundingBox();
      assert.ok(campo.width>150 && campo.x>=0 && campo.x+campo.width<=w);
      assert.match(await page.locator('#auth-screen').evaluate(e=>getComputedStyle(e).backgroundImage),w<=640?/mobile/:/login-2026/);
      if([390,1262,1920].includes(w)) await page.screenshot({path:path.join(saida,`login-${w}.png`),fullPage:true});
      await page.evaluate(()=>document.documentElement.setAttribute('data-tema','claro'));
      assert.equal(await page.locator('#auth-form').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(23, 25, 31)','Campanha mantém contraste no tema claro');
      assert.equal(await page.locator('#auth-btn').evaluate(e=>getComputedStyle(e).color),'rgb(11, 13, 16)');
      await page.evaluate(()=>document.documentElement.removeAttribute('data-tema'));
      await page.emulateMedia({reducedMotion:'reduce'});
      assert.equal(await page.locator('#auth-form .auth-marca').evaluate(e=>getComputedStyle(e,'::before').animationName),'none');
      await page.evaluate(c=>window.aplicarLoginCampanha(c),{...salva,servidorAgora:'2026-11-01T00:00:00-03:00'});
      assert.equal(await page.locator('#auth-screen').evaluate(e=>e.classList.contains('tem-fundo')),false);
      assert.equal(await page.locator('#auth-form .auth-marca>svg').isVisible(),true);
      assert.equal(await page.locator('#login-bubble-titulo').innerText(),'Bem-vindo(a) de volta! 👋');
      await page.setContent(painel);
      await page.locator('#root').evaluate(e=>e.classList.remove('hidden'));
      assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`Painel sem overflow em ${w}`);
      if(w===390) await page.screenshot({path:path.join(saida,'config-mobile.png'),fullPage:true});
      await page.close();
    }
    const page = await browser.newPage();
    await page.clock.install({time:new Date(fim-2000)});
    await page.setContent(html);
    await page.addScriptTag({content:fs.readFileSync(path.join(pasta,'login-campanha.js'),'utf8')});
    await page.addScriptTag({content:fs.readFileSync(path.join(pasta,'login-campanha-ui.js'),'utf8')});
    await page.evaluate(c=>window.aplicarLoginCampanha(c),{...salva,servidorAgora:new Date(fim-2000).toISOString()});
    assert.equal(await page.locator('#auth-screen').evaluate(e=>e.classList.contains('outubro-rosa')),true);
    await page.clock.fastForward(2100);
    assert.equal(await page.locator('#auth-screen').evaluate(e=>e.classList.contains('outubro-rosa')),false,'Tela aberta encerra sem recarregar');
    await page.close();
  } finally { await browser.close(); }
  console.log('✓ Outubro Rosa: 7 tamanhos, balão proporcional, fundo direita/baixo, laço, movimento reduzido, encerramento Brasília e tela aberta.');
}
async function testarHttp({token,DOCS,postarMultipart,putJson,pedir}){
  const cab = {Authorization:'Bearer '+token};
  const png = {nome:'campanha.png',tipo:'image/png',buffer:Buffer.from('89504e470d0a1a0a','hex')};
  assert.equal((await pedir('/api/login-custom/config')).status,401);
  assert.equal((await pedir('/api/login-custom/preview-fundo')).status,401);
  const uid = 'campanha-sem-master';
  DOCS.set('users/'+uid,{id:uid,role:'user',active:true,username:uid,cargo:'suporte',cargos:['suporte'],permissions:{sections:['suporte']}});
  const comum = {Authorization:'Bearer '+require('jsonwebtoken').sign({sub:uid,role:'user'},process.env.JWT_SECRET,{expiresIn:'1h'})};
  assert.equal((await pedir('/api/login-custom/config',comum)).status,403);
  assert.equal((await pedir('/api/login-custom/preview-fundo',comum)).status,403);
  assert.equal((await putJson('/api/login-custom',{campanhaRosa:false},comum)).status,403);
  assert.equal((await putJson('/api/login-custom',{campanhaFim:'data inválida'},cab)).status,400);
  assert.equal((await putJson('/api/login-custom',{campanhaFim:'2026-02-30T00:00-03:00'},cab)).status,400);
  assert.equal((await putJson('/api/login-custom',{campanhaRosa:'false'},cab)).status,400);
  assert.equal((await putJson('/api/login-custom',{fundoPosicao:'url(evil)'},cab)).status,400);
  assert.equal((await putJson('/api/login-custom',{campanhaRosa:true,campanhaFim:'2030-11-01T00:00-03:00',tamanhoLogin:'ampliado',fundoPosicao:'right bottom'},cab)).status,200);
  assert.equal((await postarMultipart('/api/login-custom/fundo',{},png,'fundo',cab)).status,200);
  assert.equal((await postarMultipart('/api/login-custom/fundo?mobile=1',{},png,'fundo',cab)).status,200);
  const raw = {...DOCS.get('loginCustomConfig/config')};
  assert.ok(raw.fundoArquivo && raw.fundoMobileArquivo);
  assert.equal((await pedir('/api/login-custom/fundo')).status,200);
  assert.equal((await putJson('/api/login-custom',{ativo:true,bubbleTitulo:'Outubro Rosa',campanhaRosa:true,campanhaFim:'2020-11-01T00:00-03:00'},cab)).status,200);
  const publico = JSON.parse((await pedir('/api/login-custom')).corpo);
  assert.equal(publico.campanhaExpirada,true);
  assert.equal(publico.temFundo,false);
  assert.equal(publico.temFundoMobile,false);
  assert.equal(publico.bubbleTitulo,'');
  assert.equal((await pedir('/api/login-custom/fundo')).status,404);
  assert.equal((await pedir('/api/login-custom/fundo?mobile=1')).status,404);
  assert.equal(DOCS.get('loginCustomConfig/config').fundoArquivo,raw.fundoArquivo);
  assert.equal((await pedir('/api/login-custom/preview-fundo',cab)).status,200);
  const admin = JSON.parse((await pedir('/api/login-custom/config',cab)).corpo);
  assert.equal(admin.temFundo,true);
  assert.equal(admin.fundoArquivo,undefined);
  assert.equal((await putJson('/api/login-custom',{campanhaRosa:false},cab)).status,200);
  assert.equal((await pedir('/api/login-custom/fundo')).status,200);
  console.log('✓ Campanha HTTP: Master configura; datas/posição inválidas bloqueadas; expiração pública sem apagar; preview protegido e controle manual.');
}
module.exports={testarHttp,testarVisual};
if(require.main===module) testarVisual().catch(e=>{console.error(e);process.exitCode=1;});
