const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
let src=fs.readFileSync(__dirname+'/public/entregas-analise.js','utf8');
if(process.argv.includes('--sabotagem'))src=src.replace('manual?num(r.entrega)','manual?num(r.entrega)+num(r.itensManuais?.[0]?.quantidade)');
const contexto={module:{exports:{}}};vm.runInNewContext(src,contexto);const a=contexto.module.exports;
const exemplo={data:'2026-10-02',unidade:'CG',entregador:'Luís Fernando',valorEntregas:100,entrega:10,quantTotal:10,valor:100,garantido:0,itensManuais:[{campo:'retorno',quantidade:1,valor:10,somarNoTotal:false},{campo:'extra',quantidade:2,valor:12,somarNoTotal:false}]};
const r=a.normalizar(exemplo);assert.equal(r.entrega,10);assert.equal(r.retorno,1);assert.equal(r.extra,2);assert.equal(a.somar([r]).tm,10);assert.equal(r.valor,100);
const legado=a.normalizar({entrega:7,retorno:1,extra:2,valor:100,ajudaCusto:8,quantTotal:10});assert.equal(legado.entrega,10);assert.equal(a.somar([legado]).tm,10);
assert.equal(a.normalizar({...exemplo,garantido:20,ajudaCusto:2}).ajudaCusto,22);
assert.equal(a.somar([]).tm,null);assert.equal(a.variacao(10,0),null);assert.equal(a.variacao(20,10),100);
const rows=[r,a.normalizar({...exemplo,data:'2026-09-25',unidade:'B',entregador:'Luan',valor:50})];
const f={inicio:'2026-10-01',fim:'2026-10-03',unidades:['CG'],nome:'luis',dia:'5'};
assert.equal(a.filtrar(rows,f).length,1);assert.equal(a.filtrar(rows,{...f,dia:'1'}).length,0);
assert.equal(a.filtrar(rows,{...f,nome:'<script>'}).length,0);
const estados={entregadores:null,unidades:null,lancamentos:null,grafico:null};a.sincronizar(f,estados);
estados.entregadores.inicio='2025-01-01';estados.entregadores.unidades.push('B');assert.equal(estados.unidades.inicio,'2026-10-01');assert.equal(f.unidades.length,1);
a.sincronizar(f,estados);assert.equal(estados.entregadores.inicio,'2026-10-01');assert.equal(estados.entregadores.unidades.length,1);
assert.equal(a.periodo('30dias','2026-10-03').inicio,'2026-09-04');assert.equal(a.periodo('trimestre','2026-10-03').inicio,'2026-10-01');
assert.equal(a.periodo('ano','2026-10-03').inicio,'2026-01-01');assert.equal(a.comparar({...f,inicio:'2024-02-29',fim:'2024-02-29'},'ano').inicio,'2023-02-28');
assert.equal(a.comparar({...f,inicio:'2026-03-31',fim:'2026-03-31'},'mes').inicio,'2026-02-28');
const s=a.serie(rows,{...f,dia:''});assert.equal(s.length,3);assert.equal(s[0].temDados,false);assert.equal(s[1].entrega,10);assert.equal(s[1].tm,10);
const h=fs.readFileSync(__dirname+'/public/entregas.html','utf8');
const k=h.slice(h.indexOf('const kpis = ['),h.indexOf("document.getElementById('kpis').innerHTML"));
let anterior=-1;for(const label of ['Entregadores ativos','Valor pago','Entregas','Ticket médio (TM)','Garantido / Encosta','Fora de área','Retorno','Extra']){const i=k.indexOf("lbl:'"+label+"'");assert.ok(i>anterior,label);anterior=i;}
const index=fs.readFileSync(__dirname+'/index.js','utf8');
const ex={require:p=>p==='./public/entregas-analise'?a:require(p),reportUtil:{fmtMoneyBR:n=>String(n||0),fmtDataBR:n=>n},nomeCanonicoUnidade:n=>n};
vm.runInNewContext(index.slice(index.indexOf('function filtrarEntregasPeriodo('),index.indexOf('async function todasEntregasPermitidas(')),ex);
assert.equal(ex.filtrarEntregasPeriodo(rows,{query:{inicio:f.inicio,fim:f.fim,nome:'luis',diaSemana:'5',unidades:'CG'}}).length,1);
const exportado=ex.prepararEntregasPorEntregador([exemplo]).linhas[0];assert.equal(exportado.quant,10);assert.equal(exportado.tm,'10');assert.equal(exportado.retorno,1);
assert.equal(ex.prepararEntregasPorUnidade([exemplo]).linhas[0].entrega,10);assert.equal(ex.prepararEntregasLancamentos([exemplo]).linhas[0].extra,2);
console.log('OK: totais/TM, manuais e legado, filtros independentes/sincronizados, dias, comparativos, datas bissextas e exportações.');
