'use strict';
const fs=require('fs'), vm=require('vm'), assert=require('assert/strict');
const html=fs.readFileSync(require('path').join(__dirname,'public/loja-status.html'),'utf8');
for(const s of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)) new vm.Script(s[1]);
const fonte=html.slice(html.indexOf('function conexaoComputadorHtml('),html.indexOf('function linkTexto('));
function testar(codigo){
  const ctx=vm.createContext({escapeHtml:v=>String(v).replace(/</g,'&lt;').replace(/>/g,'&gt;')});
  vm.runInContext(codigo,ctx);
  const linha=link=>ctx.conexaoComputadorHtml({link});
  assert.match(linha({tipo:'ethernet',mbps:100}),/Ethernet \(cabo\).*100 Mbps/);
  assert.match(linha({tipo:'ethernet',mbps:1000}),/1\.000 Mbps/);
  assert.match(linha({tipo:'wifi',mbps:300,ethernetCaida:true}),/Wi-Fi.*300 Mbps.*Ethernet caída/);
  assert.match(linha({tipo:'ethernet',nome:'Intel <Ethernet>'}),/interface: Intel &lt;Ethernet&gt;/);
  assert.equal(linha(null),'');
  assert.doesNotMatch(linha({tipo:'wifi',mbps:-1}),/Mbps/);
  assert.doesNotMatch(linha({tipo:'nenhum',mbps:100}),/Mbps/);
  assert.match(linha({tipo:'<img>'}),/&lt;img&gt;/);
}
testar(fonte);
for(const sabotada of [fonte.replace('link.mbps','undefined'),fonte.replace("wifi:'Wi-Fi'","wifi:'Ethernet'")]) assert.throws(()=>testar(sabotada));
assert.match(html,/if\(conexaoPc\) infoBits.push\(conexaoPc\);/);
assert.match(html,/if\(ap && !c.link && ap.rede/);
const servidor=fs.readFileSync(require('path').join(__dirname,'lojaStatus.js'),'utf8');
const saneamento=servidor.slice(servidor.indexOf('function numeroEntre('),servidor.indexOf('function sanitizarTailscale('));
const contexto=vm.createContext({});
vm.runInContext(saneamento,contexto);
const normalizar=rede=>contexto.sanitizarAparelho({rede}).rede;
assert.equal(normalizar({tipo:'wifi',rttMs:50,economiaDados:true}).rttMs,50);
assert.equal(normalizar({tipo:'wifi',rttMs:null}).rttMs,undefined);
assert.equal(normalizar({tipo:'wifi',rttMs:-1}).rttMs,undefined);
assert.equal(normalizar({tipo:'wifi',economiaDados:'true'}).economiaDados,undefined);
const aparelho=fs.readFileSync(require('path').join(__dirname,'public/aparelho.js'),'utf8');
new vm.Script(aparelho);
const coletor=aparelho.slice(aparelho.indexOf('  function lerRede()'),aparelho.indexOf('  // O sistema do aparelho'));
const navegador=vm.createContext({navigator:{connection:{type:'wifi',effectiveType:'4g',downlink:10,rtt:50,saveData:true}}});
vm.runInContext(coletor,navegador);
assert.equal(navegador.lerRede().rttMs,50);
assert.equal(navegador.lerRede().economiaDados,true);
console.log('OK: conexão na ficha, Ethernet/Wi-Fi, Mbps, sem dados, sem duplicação Android, escape, sintaxe e duas sabotagens.');
