// vigiaScript.js
// Gera o script de "vigia" (NOCZenith) que roda nativo no Windows de cada
// computador cadastrado em loja-status.html - fonte UNICA do conteudo do
// .ps1: tanto o botao "Baixar NOCZenith" (GET /api/loja-status/:codigo/
// computadores/:posto/vigia.ps1, ver index.js) quanto o proprio script
// RODANDO (que se autoatualiza sozinho - ver Verificar-Atualizacao mais
// abaixo) buscam o mesmo texto daqui, garantindo que o que a pessoa baixa
// manualmente e o que o autoupdate espalha sao sempre identicos.
//
// VERSAO_VIGIA precisa ser incrementada TODA VEZ que montarScriptVigia()
// mudar - e o numero que cada copia ja instalada usa pra saber se existe
// uma versao mais nova esperando (ver GET /api/loja-status/vigia-versao).
// Esquecer de bumpar significa que a mudanca nunca chega nos computadores
// que ja tem o vigia rodando (so nos que forem instalados do zero depois
// do deploy).
const VERSAO_VIGIA = 21;

const APP_BASE_URL = (process.env.APP_BASE_URL || 'https://adyen-monitor.onrender.com').replace(/\/+$/, '');

// qual pagina cada tipo de computador abre - mesmo mapeamento client-side
// de loja-status.html (paginaDoTipo), usado so pra montar a URL que o
// vigia reabre quando a janela fecha (tipo != 'interno')
function paginaDoTipo(tipo) {
  if (tipo === 'interno') return '';
  if (tipo === 'abastecimento') return 'abastecimento.html';
  return 'atendimento.html';
}

// gera o texto completo do NOCZenith-<posto>.ps1 pra um computador
// especifico. "tipo" decide o comportamento do loop:
// - 'interno' (servidor/PC sem funcao pra alguem usar): manda heartbeat de
//   verdade a cada 25s, sem gerenciar janela nenhuma.
// - outros (atendimento/abastecimento): reabre a tela de monitoramento se
//   fechar + reporta o IP local, a cada ~120s (tick rapido de 20s com
//   contador, pra nao atrasar a deteccao de acesso remoto).
// Os dois tipos, alem disso, TODO tick: (1) checam acesso remoto (AnyDesk/
// TeamViewer/DWService/etc conectado - ver Verificar-AcessoRemoto) e, numa
// cadencia bem mais espacada (~1h), (2) checam se existe uma versao nova
// do proprio script esperando (ver Verificar-Atualizacao) - se sim, baixa
// o conteudo novo, sobrescreve o proprio arquivo e reinicia sozinho.
function montarScriptVigia({ codigo, posto, tipo, agentToken }) {
  const ehInterno = tipo === 'interno';
  // segredo desse computador (ver lojaStatus.js) - vai assado no script e
  // volta no cabecalho X-NOC-Token em todo request pro servidor, provando
  // que quem fala e a maquina certa. Sem ele, o backend nao entrega comando/
  // chat nem aceita resultado/IP/alerta (fecha a brecha de que so codigo+
  // posto, que sao publicos, autorizavam tudo). O `|| ''` e so defensivo -
  // a rota vigia.ps1 sempre passa um token (garantirAgentToken)
  const tokenSeguro = String(agentToken || '').replace(/[^a-f0-9]/gi, '');
  // codigo entra CRU em varias strings PowerShell de aspas duplas (titulo da
  // janela, log, corpo do heartbeat). Dentro de "..." o PowerShell interpola
  // $(...)/$var e trata " como fim da string - entao um codigo com esses
  // caracteres viraria injecao/quebra no script que um admin baixa e roda.
  // Nenhum codigo de unidade legitimo tem `, " ou $ (tem acento, espaco e ate
  // apostrofo, que sao inofensivos em aspas duplas) - entao remover SO esses e
  // as quebras de linha fecha a brecha sem estragar nenhuma unidade real. As
  // URLs continuam usando encodeURIComponent(codigo real), cuja saida ja nao
  // tem ", $ nem crase (fica segura nas aspas duplas por conta propria).
  const codigoTextoPS = String(codigo).replace(/[`"$\r\n]/g, '');
  const urlMonitorar = `${APP_BASE_URL}/${paginaDoTipo(tipo)}?unidade=${encodeURIComponent(codigo)}&posto=${encodeURIComponent(posto)}`;
  const urlReportarIp = `${APP_BASE_URL}/api/loja-status/${encodeURIComponent(codigo)}/computadores/${encodeURIComponent(posto)}/ip-local`;
  const urlHeartbeat = `${APP_BASE_URL}/api/loja-status/heartbeat`;
  const urlAcessoRemoto = `${APP_BASE_URL}/api/loja-status/${encodeURIComponent(codigo)}/computadores/${encodeURIComponent(posto)}/acesso-remoto`;
  const urlComandoResultado = `${APP_BASE_URL}/api/loja-status/${encodeURIComponent(codigo)}/computadores/${encodeURIComponent(posto)}/comando-resultado`;
  const urlChatResponder = `${APP_BASE_URL}/api/loja-status/${encodeURIComponent(codigo)}/computadores/${encodeURIComponent(posto)}/chat-responder`;
  const urlTelemetria = `${APP_BASE_URL}/api/loja-status/${encodeURIComponent(codigo)}/computadores/${encodeURIComponent(posto)}/telemetria`;
  const urlVersao = `${APP_BASE_URL}/api/loja-status/vigia-versao`;
  const urlScriptProprio = `${APP_BASE_URL}/api/loja-status/${encodeURIComponent(codigo)}/computadores/${encodeURIComponent(posto)}/vigia.ps1?tipo=${encodeURIComponent(tipo)}`;
  const nomeTarefa = 'NOCZenith_' + posto;

  const cabecalhoInterno = [
    '# O que isso faz, rodando escondido em segundo plano: manda direto pro',
    '# NoPulso o sinal de que esse computador esta ligado e conectado (aparece',
    '# online em Status das Lojas) - sem precisar manter nenhuma janela aberta.',
    '# Continua podendo abrir o app fixado na barra de tarefas quando quiser,',
    '# pra fazer login/usar o NoPulso normal - isso nao tem nenhum conflito com',
    '# o NOCZenith rodando por baixo. Tambem avisa SO o Master (nao aparece pro',
    '# resto do time) quando alguem se conecta nessa maquina por AnyDesk,',
    '# TeamViewer, DWService ou qualquer outra ferramenta de acesso remoto.',
    '# Se o Master mandar uma mensagem, abre uma janelinha de chat no canto',
    '# da tela avisando - da pra responder direto por ela.',
    '# Se atualiza sozinho quando sai uma versao nova (sem precisar reinstalar).',
  ];
  const cabecalhoOutros = [
    '# O que isso faz, rodando escondido em segundo plano:',
    '# 1) Reabre a tela de monitoramento sozinho se alguem fechar ela sem querer.',
    '# 2) Manda pro NoPulso o IP da rede LOCAL desse computador (pra acesso',
    '#    remoto no dia a dia - aparece em Status das Lojas, no card desse',
    '#    computador).',
    '# 3) Avisa SO o Master (nao aparece pro resto do time) quando alguem se',
    '#    conecta nessa maquina por AnyDesk, TeamViewer, DWService ou',
    '#    qualquer outra ferramenta de acesso remoto.',
    '# 4) Se atualiza sozinho quando sai uma versao nova (sem precisar reinstalar).',
  ];
  const linhasComuns = [
    '# NOCZenith - ' + codigoTextoPS + ' / ' + posto,
    '#',
    ...(ehInterno ? cabecalhoInterno : cabecalhoOutros),
    '#',
    '# COMO INSTALAR:',
    '# Jeito 1 (recomendado, sem bloqueio do Windows): na tela NOC Zenith, no',
    '#   NoPulso, clique em "Copiar comando" desse computador, cole no PowerShell',
    '#   da loja e aperte Enter. Pronto.',
    '#',
    '# Jeito 2 (a partir deste arquivo baixado): o Windows 11 (Controle de',
    '#   Aplicativo Inteligente) bloqueia .ps1 baixado da internet. Pra liberar:',
    '#   1) Abra o PowerShell (menu Iniciar > digite PowerShell).',
    '#   2) Cole, trocando pelo caminho onde salvou (mantenha as aspas):',
    '#        Unblock-File "C:\\...\\NOCZenith.ps1"',
    '#      (tira o selo de "veio da internet" que causa o bloqueio)',
    '#   3) Cole:',
    '#        powershell -ExecutionPolicy Bypass -File "C:\\...\\NOCZenith.ps1"',
    '#',
    '# Depois de instalar, o NOCZenith se COPIA sozinho pra uma pasta fixa',
    '# (%LOCALAPPDATA%\\NOCZenith) e passa a rodar de la - entao o arquivo que',
    '# voce baixou pode ser APAGADO. Ele tambem se atualiza sozinho dai pra frente.',
    '',
    '# -Servico: instancia de BOOT (tarefa SYSTEM, criada so quando a instalacao',
    '# rodou como Administrador). Sobe junto com o Windows, ANTES de qualquer',
    '# login - e o que corrigiu o parque inteiro ficar mudo depois de um',
    '# reinicio: a tarefa de login nunca disparava porque ninguem logava. Essa',
    '# instancia nao tem tela (roda como SYSTEM), entao cede a vez pra',
    '# instancia de login (com janela de chat) quando ela esta viva - ver',
    '# UiEstaAtiva no loop.',
    'param([switch]$Loop, [switch]$Servico)',
    '',
    '$NomeTarefa = "' + nomeTarefa + '"',
    '$InicioScript = [DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()',
    '',
    '# segredo desse computador - autentica todo request pro NoPulso (cabecalho',
    '# X-NOC-Token). Nao compartilhe esse arquivo: quem tiver esse token fala',
    '# como essa maquina. O NOCZenith se atualiza sozinho carregando o token.',
    '$AgentToken = "' + tokenSeguro + '"',
    '$CabecalhosAgente = @{ "X-NOC-Token" = $AgentToken }',
    '',
    '# ---- log local (arquivo texto do lado do .ps1) - sem isso, todo erro',
    '# ficava mudo (-ErrorAction SilentlyContinue + catch {} em toda chamada de',
    '# rede, de proposito, pra nunca derrubar o loop) e nao tinha como saber,',
    '# olhando so o computador, POR QUE ele nao aparece online no NoPulso. So',
    '# grava eventos que importam pro diagnostico (falha, comando, chat,',
    '# atualizacao, inicio) - nao todo heartbeat bem-sucedido, senao o arquivo',
    '# cresce sem parar. Trunca sozinho se passar de ~300KB, mantendo so o',
    '# final (mais recente e mais util pra debugar um problema atual).',
    '$CaminhoLog = Join-Path (Split-Path -Parent $PSCommandPath) "NOCZenith.log"',
    'function Escrever-Log($mensagem) {',
    '  try {',
    '    if ((Test-Path $CaminhoLog) -and ((Get-Item $CaminhoLog).Length -gt 300KB)) {',
    '      $resto = Get-Content $CaminhoLog -Tail 400',
    '      Set-Content -Path $CaminhoLog -Value $resto -Encoding UTF8',
    '    }',
    '    "$([DateTime]::Now.ToString("yyyy-MM-dd HH:mm:ss")) - $mensagem" | Out-File -FilePath $CaminhoLog -Append -Encoding UTF8',
    '  } catch {}',
    '}',
    '',
    '# ---- coordenacao entre as DUAS instancias possiveis (boot x login).',
    '# Quando a instalacao roda como Administrador, existe uma tarefa de BOOT',
    '# (SYSTEM, sobe com o Windows, sem tela) alem da tarefa de LOGIN (do',
    '# usuario, com a janela de chat). As duas nao podem trabalhar ao mesmo',
    '# tempo - seria heartbeat dobrado e, pior, COMANDO executado duas vezes.',
    '# A regra: a instancia de login carimba este arquivo a cada tick; a de',
    '# boot, vendo carimbo fresco (<90s), fica em espera. Se o usuario deslogar',
    '# (o carimbo envelhece), a de boot reassume em ate 2 ticks - a maquina',
    '# nunca fica muda, logada ou nao.',
    '$CaminhoFlagUi = Join-Path (Split-Path -Parent $PSCommandPath) "ui-ativa.flag"',
    'function Marcar-UiAtiva {',
    '  try { [DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds() | Set-Content -Path $CaminhoFlagUi -Force } catch {}',
    '}',
    'function UiEstaAtiva {',
    '  try {',
    '    if (-not (Test-Path $CaminhoFlagUi)) { return $false }',
    '    $t = [int64]((Get-Content $CaminhoFlagUi -First 1))',
    '    return (([DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds() - $t) -lt 90000)',
    '  } catch { return $false }',
    '}',
    '',
    '# ---- deteccao de acesso remoto (AnyDesk, TeamViewer, DWService, RustDesk,',
    '# UltraViewer, VNC, Chrome Remote Desktop - ou qualquer outra que rode como',
    '# processo do Windows). Dedup POR PROCESSO: enquanto o processo tem conexao',
    '# estabelecida, alerta so UMA vez (esquece quando o processo some/cai a',
    '# conexao; se reaparecer depois, avisa de novo). Importante: NAO deduplica',
    '# por IP - ferramentas de nuvem (Splashtop/LogMeIn/GoToMyPC) ficam ligadas',
    '# 24h e a nuvem delas (AWS:443) troca de IP toda hora; dedup por IP fazia',
    '# cada troca virar um "acesso novo" e enchia o Master de alertas falsos. Por',
    '# isso essas 3 (que so mantem batimento de nuvem, sem indicar sessao real)',
    '# ficam FORA da lista. Best-effort: cobre os casos comuns, nao e garantia',
    '# absoluta pra toda ferramenta que existe.',
    '$UrlAcessoRemoto = "' + urlAcessoRemoto + '"',
    '# ferramentas de nuvem sempre-ligadas (Splashtop SRServer/SRManager, LogMeIn',
    '# LMIGuardianSvc, GoToMyPC g2mcomm/g2svc) foram REMOVIDAS de proposito: o',
    '# batimento 24h delas nao indica sessao de verdade e so gerava alerta falso.',
    '$ProcessosAcessoRemoto = @(',
    '  "AnyDesk", "TeamViewer", "TeamViewer_Service", "dwagent", "dwagsvc",',
    '  "rustdesk", "UltraViewer_Desktop", "UltraViewer_Service", "remoting_host",',
    '  "Supremo", "vncserver", "winvnc", "tvnserver"',
    ')',
    '$JaAvisados = New-Object System.Collections.Generic.HashSet[string]',
    '',
    'function Verificar-AcessoRemoto {',
    '  $vistosAgora = New-Object System.Collections.Generic.HashSet[string]',
    '  foreach ($nomeProc in $ProcessosAcessoRemoto) {',
    '    $procs = Get-Process -Name $nomeProc -ErrorAction SilentlyContinue',
    '    foreach ($p in $procs) {',
    '      $conexoes = Get-NetTCPConnection -State Established -OwningProcess $p.Id -ErrorAction SilentlyContinue',
    '      foreach ($c in $conexoes) {',
    '        if ($c.RemoteAddress -eq "127.0.0.1" -or $c.RemoteAddress -eq "::1") { continue }',
    '        $chave = "$nomeProc"',
    '        # $vistosAgora.Add devolve $false se a chave ja estava la: garante 1',
    '        # alerta por processo por tick (mesmo com varias conexoes abertas)',
    '        if (-not $vistosAgora.Add($chave)) { continue }',
    '        if (-not $JaAvisados.Contains($chave)) {',
    '          try {',
    '            $detalhe = "$nomeProc ($($c.RemoteAddress):$($c.RemotePort))"',
    '            $corpoAlerta = @{ detalhe = $detalhe } | ConvertTo-Json',
    '            Invoke-RestMethod -Uri $UrlAcessoRemoto -Method Post -ContentType "application/json" -Headers $CabecalhosAgente -Body $corpoAlerta -TimeoutSec 10 -ErrorAction SilentlyContinue | Out-Null',
    '          } catch {}',
    '        }',
    '      }',
    '    }',
    '  }',
    '  $script:JaAvisados = $vistosAgora',
    '}',
    '',
    // ---- estado do servico do AnyDesk ----
    // O NOC sabia dizer que a maquina esta VIVA e sabia avisar quando alguem
    // se conecta por acesso remoto - mas nao sabia que o AnyDesk tinha
    // PARADO. O card ficava verde com o acesso remoto morto, e isso so era
    // descoberto na hora de precisar entrar (foi o caso da STC-Servidor:
    // offline no AnyDesk, online no NOCZenith, Windows rodando normal).
    //
    // Leitura de contador do Windows, custa milissegundos. Procura por
    // PADRAO pelo mesmo motivo do comando de reset: o nome do servico muda
    // com a versao e o tipo de instalacao.
    //
    // NAO INSTALADO devolve null, nao "parado": a maioria das maquinas de
    // loja nao tem AnyDesk, e dizer que o servico dessas caiu encheria o
    // painel de amarelo por uma coisa que nao existe ali.
    'function Medir-AnyDesk {',
    '  try {',
    '    $svc = @(Get-Service -ErrorAction SilentlyContinue |',
    '      Where-Object { $_.Name -like "AnyDesk*" -or $_.DisplayName -like "AnyDesk*" })',
    '    if (-not $svc) { return $null }',
    '    if ($svc | Where-Object { $_.Status -eq "Running" }) { return "Running" }',
    '    return "$($svc[0].Status)"',
    '  } catch { return $null }',
    '}',
    '',
    '# ---- saude do HD ----------------------------------------------------',
    '# Le o que o Windows ja sabe do disco (SMART + espaco livre). Nao roda',
    '# teste de superficie nem nada que segure a maquina: e leitura de',
    '# contador, custa milissegundos. Cada informacao vem de um lugar que pode',
    '# nao existir naquela maquina (contador de confiabilidade pede permissao,',
    '# disco USB nao expoe SMART), entao TUDO esta em try/catch separado e o',
    '# que faltar simplesmente nao vai - o servidor trata campo ausente como',
    '# "nao sei", nunca como zero.',
    '$UrlTelemetria = "' + urlTelemetria + '"',
    'function Medir-Disco {',
    '  $d = @{ discos = @(); volumes = @() }',
    '  try {',
    '    foreach ($p in @(Get-PhysicalDisk -ErrorAction SilentlyContinue)) {',
    '      $saude = "desconhecida"',
    '      switch ("$($p.HealthStatus)") {',
    '        "Healthy"   { $saude = "saudavel" }',
    '        "Warning"   { $saude = "atencao" }',
    '        "Unhealthy" { $saude = "ruim" }',
    '      }',
    '      $item = @{ modelo = "$($p.FriendlyName)"; tipo = "$($p.MediaType)"; saude = $saude }',
    '      if ($p.Size) { $item.tamanhoGb = [math]::Round($p.Size / 1GB, 1) }',
    '      try {',
    '        $rc = $p | Get-StorageReliabilityCounter -ErrorAction SilentlyContinue',
    '        if ($rc) {',
    '          if ($rc.Temperature -ne $null -and $rc.Temperature -gt 0) { $item.temperaturaC = [int]$rc.Temperature }',
    '          if ($rc.PowerOnHours -ne $null) { $item.horasLigado = [int]$rc.PowerOnHours }',
    '          if ($rc.Wear -ne $null) { $item.desgastePct = [int]$rc.Wear }',
    '          if ($rc.ReadErrorsUncorrected -ne $null) { $item.errosLeitura = [int]$rc.ReadErrorsUncorrected }',
    '        }',
    '      } catch {}',
    '      $d.discos += $item',
    '    }',
    '  } catch { Escrever-Log "Falha ao ler discos fisicos: $($_.Exception.Message)" }',
    '  try {',
    '    # SMART classico: HD antigo as vezes so responde por aqui. Nao da pra',
    '    # amarrar com seguranca a qual disco a instancia pertence quando tem',
    '    # mais de um, entao com varios discos entra como uma linha propria em',
    '    # vez de acusar o disco errado.',
    '    $falhando = @(Get-CimInstance -Namespace root\\wmi -ClassName MSStorageDriver_FailurePredictStatus -ErrorAction SilentlyContinue |',
    '      Where-Object { $_.PredictFailure })',
    '    if ($falhando.Count -gt 0) {',
    '      if ($d.discos.Count -eq 1) { $d.discos[0].predicaoFalha = $true }',
    '      else { $d.discos += @{ modelo = "SMART (disco nao identificado)"; saude = "ruim"; predicaoFalha = $true } }',
    '    }',
    '  } catch {}',
    '  try {',
    '    foreach ($v in @(Get-Volume -ErrorAction SilentlyContinue | Where-Object { $_.DriveLetter -and $_.Size -gt 0 -and $_.DriveType -eq "Fixed" })) {',
    '      $d.volumes += @{ letra = "$($v.DriveLetter):"; totalGb = [math]::Round($v.Size / 1GB, 1); livreGb = [math]::Round($v.SizeRemaining / 1GB, 1) }',
    '    }',
    '  } catch { Escrever-Log "Falha ao ler volumes: $($_.Exception.Message)" }',
    '  return $d',
    '}',
    '',
    '# ---- varredura da rede local ----------------------------------------',
    '# Le a tabela de vizinhos (ARP) que o Windows ja mantem de quem esse',
    '# computador conversou na rede da loja, e depois resolve o NOME de cada um',
    '# por DNS reverso / NetBIOS. Nao e varredura de portas nem ping em faixa',
    '# de IP: e o mesmo tipo de consulta que qualquer maquina da rede faz o dia',
    '# todo, entao nao vira scanner nem acorda o IDS do shopping.',
    'function Varrer-RedeLocal {',
    '  $lista = @()',
    '  try {',
    '    $viz = @(Get-NetNeighbor -AddressFamily IPv4 -ErrorAction SilentlyContinue |',
    '      Where-Object { $_.State -eq "Reachable" -or $_.State -eq "Stale" -or $_.State -eq "Permanent" })',
    '    foreach ($n in $viz) {',
    '      $ip = "$($n.IPAddress)"',
    '      $mac = "$($n.LinkLayerAddress)"',
    '      if (-not $ip -or -not $mac) { continue }',
    '      # so IP de rede PRIVADA (a LAN da loja). Isso ja descarta de uma vez',
    '      # link-local, multicast e broadcast, que estao sempre na tabela ARP e',
    '      # nao sao aparelho nenhum',
    '      $o = $ip.Split(".")',
    '      $priv = ($o[0] -eq "10") -or ($o[0] -eq "192" -and $o[1] -eq "168") -or ($o[0] -eq "172" -and [int]$o[1] -ge 16 -and [int]$o[1] -le 31)',
    '      if (-not $priv) { continue }',
    '      if ($mac -eq "FF-FF-FF-FF-FF-FF" -or $mac -eq "00-00-00-00-00-00" -or $mac -like "01-00-5E-*") { continue }',
    '      $lista += @{ ip = $ip; mac = $mac; nome = $null }',
    '    }',
    '  } catch { Escrever-Log "Falha na varredura da rede: $($_.Exception.Message)" }',
    '  # NOME do aparelho. Duas tentativas, da mais barata pra mais cara:',
    '  #   1) DNS reverso - se a loja tem servidor/roteador que registra os',
    '  #      nomes, resolve na hora (milissegundos com -QuickTimeout).',
    '  #   2) NetBIOS (nbtstat) - como maquina Windows se anuncia na LAN, e o',
    '  #      que responde quando nao ha DNS interno. Custa ate ~2s por IP que',
    '  #      NAO responde, entao so entra pra quem o DNS nao resolveu.',
    '  # Tudo isso dentro de um orcamento de 10s no total: essa funcao roda no',
    '  # meio do loop de heartbeat (25s) e atrasar o heartbeat e pior do que',
    '  # ficar sem o nome de alguns aparelhos - o nome que faltar hoje vem na',
    '  # varredura da proxima hora.',
    '  $cronoNome = [Diagnostics.Stopwatch]::StartNew()',
    '  foreach ($item in $lista) {',
    '    if ($cronoNome.Elapsed.TotalSeconds -gt 10) { break }',
    '    try {',
    '      $r = Resolve-DnsName -Name $item.ip -Type PTR -QuickTimeout -DnsOnly -ErrorAction SilentlyContinue |',
    '        Select-Object -First 1 -ExpandProperty NameHost',
    '      if ($r) { $item.nome = ("$r" -split "\\.")[0] }',
    '    } catch {}',
    '  }',
    '  foreach ($item in $lista) {',
    '    if ($item.nome) { continue }',
    '    if ($cronoNome.Elapsed.TotalSeconds -gt 10) { break }',
    '    try {',
    '      # a linha do nome NetBIOS vem como: NOME  <00>  UNIQUE  Registered',
    '      $saida = (nbtstat -A $item.ip 2>$null)',
    '      foreach ($l in $saida) {',
    '        if ($l -match "^\\s*(\\S+)\\s+<00>\\s+UNIQUE") { $item.nome = $matches[1]; break }',
    '      }',
    '    } catch {}',
    '  }',
    '  return $lista',
    '}',
    '',
    '# ---- LINK FISICO (pedido do Master: monitorar se o computador esta com',
    '# Ethernet ou nao). Le so o que o Windows ja sabe das placas de rede, sem',
    '# ping nem nada externo - custa milissegundos.',
    '#',
    '# Por que isso importa: "offline" no NOC so quer dizer "parou de falar".',
    '# Quando o cabo cai numa maquina que TAMBEM tem Wi-Fi, ela continua',
    '# falando - e ninguem ficava sabendo que ela caiu pro Wi-Fi ate a loja',
    '# reclamar de lentidao. Esta funcao e o que torna esse caso visivel.',
    '# Quando a Ethernet e o UNICO caminho, a maquina some do ar e quem conta',
    '# a historia e o alerta de queda; ai o valor daqui e o registro do',
    '# ultimo link conhecido, gravado no evento da queda.',
    '#',
    '# Get-NetAdapter existe do Windows 8/Server 2012 pra frente. Em maquina',
    '# mais velha cai no Win32_NetworkAdapter, que da menos detalhe mas',
    '# responde a pergunta principal (e cabo ou nao e).',
    'function Medir-Link {',
    '  $r = @{ tipo = "nenhum"; ethernetCaida = $false }',
    '  try {',
    '    $todas = @(Get-NetAdapter -Physical -ErrorAction Stop)',
    '    if ($todas.Count -eq 0) { return $r }',
    '    $classificar = {',
    '      param($a)',
    '      $m = "$($a.PhysicalMediaType) $($a.MediaType) $($a.InterfaceDescription)"',
    '      if ($m -match "802\\.11|Wireless|Wi-?Fi") { return "wifi" }',
    '      if ($m -match "802\\.3|Ethernet") { return "ethernet" }',
    '      return "outro"',
    '    }',
    '    $ativas = @($todas | Where-Object { $_.Status -eq "Up" })',
    '    # tem placa de cabo instalada mas ela NAO esta Up = cabo solto,',
    '    # switch morto ou porta queimada. E exatamente o alerta pedido.',
    '    $temEthernet = @($todas | Where-Object { (& $classificar $_) -eq "ethernet" })',
    '    $ethernetUp = @($ativas | Where-Object { (& $classificar $_) -eq "ethernet" })',
    '    $r.ethernetCaida = ($temEthernet.Count -gt 0 -and $ethernetUp.Count -eq 0)',
    '    if ($ativas.Count -eq 0) { return $r }',
    '    # a que vale e a Ethernet, se houver - e por ela que a loja deveria',
    '    # estar falando. So cai pro Wi-Fi quando nao ha cabo no ar.',
    '    $principal = if ($ethernetUp.Count -gt 0) { $ethernetUp[0] } else { $ativas[0] }',
    '    $r.tipo = (& $classificar $principal)',
    '    $r.nome = [string]$principal.Name',
    '    # LinkSpeed vem como texto ("1 Gbps", "100 Mbps") - vira numero em',
    '    # Mbps pra dar pra comparar (placa gigabit negociando 100 = cabo ruim)',
    '    try {',
    '      if ("$($principal.LinkSpeed)" -match "([\\d\\.,]+)\\s*(G|M|K)?bps") {',
    '        $n = [double](($matches[1]) -replace ",", ".")',
    '        switch ($matches[2]) {',
    '          "G" { $r.mbps = [int]($n * 1000) }',
    '          "M" { $r.mbps = [int]$n }',
    '          "K" { $r.mbps = [int]($n / 1000) }',
    '          default { $r.mbps = [int]($n / 1000000) }',
    '        }',
    '      }',
    '    } catch {}',
    '    return $r',
    '  } catch {',
    '    # Windows sem o modulo NetAdapter: resposta simplificada',
    '    try {',
    '      $velhas = @(Get-CimInstance Win32_NetworkAdapter -Filter "PhysicalAdapter=True AND NetEnabled=True" -ErrorAction SilentlyContinue)',
    '      foreach ($a in $velhas) {',
    '        if ("$($a.Name)" -match "Wireless|Wi-?Fi|802\\.11") { $r.tipo = "wifi" }',
    '        elseif ($r.tipo -ne "ethernet") { $r.tipo = "ethernet"; $r.nome = [string]$a.Name }',
    '      }',
    '    } catch {}',
    '    return $r',
    '  }',
    '}',
    '',
    '# ---- REINICIO / DESLIGAMENTO. Lido UMA vez, quando o agente sobe, e',
    '# carregado em todo heartbeat dali pra frente. Isso e de proposito e e o',
    '# que torna a deteccao confiavel: enquanto o agente vive, a maquina nao',
    '# reiniciou, entao o numero nao muda. Se o servidor ve um bootEm',
    '# diferente, so ha uma explicacao - a maquina reiniciou e o agente subiu',
    '# de novo. Nao ha como confundir com queda de rede (numa queda o agente',
    '# nem morre, e quando a rede volta ele manda o MESMO bootEm).',
    '$BootEm = $null',
    '$DesligamentoInesperado = $false',
    'try {',
    '  $b = (Get-CimInstance Win32_OperatingSystem -ErrorAction Stop).LastBootUpTime',
    '  if ($b) { $BootEm = [int64]([DateTimeOffset]::new($b.ToUniversalTime(), [TimeSpan]::Zero).ToUnixTimeMilliseconds()) }',
    '} catch { Escrever-Log "Nao consegui ler o LastBootUpTime: $($_.Exception.Message)" }',
    '# 6008 = "o desligamento anterior foi inesperado" (queda de energia, trava,',
    '# botao segurado). So conta se o evento for RECENTE em relacao ao boot -',
    '# senao um 6008 de semanas atras marcaria toda subida como anormal.',
    'try {',
    '  $ev = Get-WinEvent -FilterHashtable @{ LogName = "System"; Id = 6008 } -MaxEvents 1 -ErrorAction Stop',
    '  if ($ev -and $BootEm) {',
    '    $evMs = [int64]([DateTimeOffset]::new($ev.TimeCreated.ToUniversalTime(), [TimeSpan]::Zero).ToUnixTimeMilliseconds())',
    '    if ([math]::Abs($BootEm - $evMs) -lt 900000) { $DesligamentoInesperado = $true }',
    '  }',
    '} catch { }',
    '',
    '# manda os dois blocos numa chamada so, fora do heartbeat (ver',
    '# nocMaquina.js). Falha aqui NUNCA pode derrubar o loop: e informacao',
    '# de apoio, o que nao pode faltar e a presenca da maquina.',
    '# ha quanto tempo o Windows esta sem reiniciar. LastBootUpTime e o uptime',
    '# REAL da maquina - nao confundir com o tempo que a janela do NoPulso esta',
    '# aberta, que zera a cada reload. Regra da casa: reiniciar 1x por semana.',
    'function Medir-Uptime {',
    '  try {',
    '    $boot = (Get-CimInstance Win32_OperatingSystem -ErrorAction SilentlyContinue).LastBootUpTime',
    '    if (-not $boot) { return $null }',
    '    return [math]::Round(((Get-Date) - $boot).TotalHours, 1)',
    '  } catch { return $null }',
    '}',
    '',
    '# ---- SONDA DA IMPRESSORA (Zebra, porta 9100). O alarme de rede so pega',
    '# "sumiu da rede" - e demora ~2h. Uma Zebra sem papel, com a cabeca aberta',
    '# ou com a fila travada continua respondendo o ping: pra operacao ela',
    '# parou, pro NOC ela estava ok. Aqui o agente PERGUNTA (~HS) e devolve o',
    '# texto CRU - quem interpreta e o servidor (impressoraStatus.js), porque',
    '# mudar parse no servidor e deploy, e mudar aqui custa versao nova nas 52',
    '# maquinas.',
    '# A lista de quem sondar vem na RESPOSTA da telemetria - so entra quem o',
    '# Master marcou como impressora monitorada na tela. Lista vazia = nao',
    '# abre socket nenhum.',
    '$ImpressorasPraSondar = @()',
    'function Sondar-Impressora($ip) {',
    '  $cli = $null',
    '  try {',
    '    $cli = New-Object System.Net.Sockets.TcpClient',
    '    # timeout curto: o loop e de 20-25s, a sonda nao pode segurar o tick',
    '    $conexao = $cli.BeginConnect($ip, 9100, $null, $null)',
    '    if (-not $conexao.AsyncWaitHandle.WaitOne(2000, $false)) { $cli.Close(); return "" }',
    '    $cli.EndConnect($conexao)',
    '    $cli.SendTimeout = 2000; $cli.ReceiveTimeout = 2000',
    '    $st = $cli.GetStream()',
    '    $b = [System.Text.Encoding]::ASCII.GetBytes("~HS")',
    '    $st.Write($b, 0, $b.Length); $st.Flush()',
    '    $buf = New-Object byte[] 1024',
    '    $sb = New-Object System.Text.StringBuilder',
    '    $limite = (Get-Date).AddSeconds(2)',
    '    while ((Get-Date) -lt $limite) {',
    '      if ($st.DataAvailable) {',
    '        $n = $st.Read($buf, 0, $buf.Length)',
    '        if ($n -le 0) { break }',
    '        [void]$sb.Append([System.Text.Encoding]::ASCII.GetString($buf, 0, $n))',
    '        $limite = (Get-Date).AddMilliseconds(400)',
    '      } else { Start-Sleep -Milliseconds 80 }',
    '    }',
    '    $st.Close()',
    '    return $sb.ToString()',
    '  } catch { return "" } finally { if ($cli) { try { $cli.Close() } catch {} } }',
    '}',
    'function Sondar-Impressoras {',
    '  if (-not $ImpressorasPraSondar -or $ImpressorasPraSondar.Count -eq 0) { return $null }',
    '  $out = @()',
    '  foreach ($imp in $ImpressorasPraSondar) {',
    '    if (-not $imp.ip) { continue }',
    '    $out += @{ mac = $imp.mac; ip = $imp.ip; bruto = (Sondar-Impressora $imp.ip) }',
    '  }',
    '  if ($out.Count -eq 0) { return $null }',
    '  return $out',
    '}',
    '',
    'function Enviar-Telemetria($disco, $dispositivos, $impressoras) {',
    '  try {',
    '    $corpo = @{}',
    '    if ($disco) { $corpo.disco = $disco }',
    '    # o uptime vai junto SEMPRE que houver telemetria - e uma linha so, e',
    '    # e o que sustenta o lembrete semanal de reboot',
    '    $up = Medir-Uptime',
    '    if ($up -ne $null) { $corpo.uptimeHoras = $up }',
    '    if ($dispositivos -and $dispositivos.Count -gt 0) { $corpo.dispositivos = $dispositivos }',
    '    if ($impressoras -and $impressoras.Count -gt 0) { $corpo.statusImpressoras = $impressoras }',
    '    # boot e link viajam junto: em computador de atendimento quem bate o',
    '    # heartbeat e o navegador, entao a telemetria e o UNICO canal que o',
    '    # NOCZenith tem pra contar que a maquina reiniciou ou perdeu o cabo',
    '    if ($BootEm -ne $null) { $corpo.bootEm = $BootEm; $corpo.desligamentoInesperado = $DesligamentoInesperado }',
    '    try { $l = Medir-Link; if ($l) { $corpo.link = $l } } catch {}',
    '    # em maquina de atendimento quem bate o heartbeat e o navegador, entao',
    '    # a telemetria e o unico canal pra contar o estado do AnyDesk',
    '    try { $a = Medir-AnyDesk; if ($a -ne $null) { $corpo.anydeskServico = $a } } catch {}',
    '    if ($corpo.Count -eq 0) { return }',
    '    # -Depth 5: sem isso o ConvertTo-Json (padrao 2) transforma a lista de',
    '    # discos/volumes em texto e o servidor recebe lixo',
    '    $json = $corpo | ConvertTo-Json -Depth 5',
    '    # a resposta traz quais impressoras sondar dali pra frente (servidor',
    '    # >= v19). Servidor antigo nao manda o campo e a lista fica vazia -',
    '    # nenhum socket e aberto, nada muda.',
    '    $r = Invoke-RestMethod -Uri $UrlTelemetria -Method Post -ContentType "application/json" -Headers $CabecalhosAgente -Body $json -TimeoutSec 15',
    '    if ($r -and $r.sondarImpressoras) { $script:ImpressorasPraSondar = @($r.sondarImpressoras) }',
    '  } catch { Escrever-Log "Falha ao enviar telemetria: $($_.Exception.Message)" }',
    '}',
    '',
    '# ---- autoatualizacao: confere de vez em quando (nao a cada tick - e',
    '# barato mas nao precisa ser instantaneo) se o servidor tem uma versao',
    '# mais nova que a que esse arquivo tem gravada. Se tiver, baixa o .ps1',
    '# novo (o MESMO conteudo que o botao "Baixar NOCZenith" gera hoje pra',
    '# esse computador), sobrescreve o proprio arquivo e reinicia rodando a',
    '# versao nova - sem precisar reinstalar na mao. So sobrescreve se o',
    '# conteudo baixado parecer valido (comeca com "# NOCZenith"), pra nunca',
    '# gravar um arquivo vazio/quebrado por causa de uma falha de rede.',
    '$VersaoScript = ' + VERSAO_VIGIA,
    '$UrlVersao = "' + urlVersao + '"',
    '$UrlScriptProprio = "' + urlScriptProprio + '"',
    '',
    '# Fecha a janela de chat ANTES do processo sair. A ordem importa: se o',
    '# processo morre com a janela viva, o Tick seguinte (1s) e invocado como',
    '# delegate num runspace ja fechado e o WinForms abre a caixa de erro na',
    '# tela da loja. Parar o pipeline aqui, com o processo ainda de pe, faz a',
    '# excecao cair no try/catch de dentro da propria janela.',
    '# Existe so no tipo interno; nos outros as variaveis sao nulas e as',
    '# chamadas viram no-op.',
    'function Encerrar-JanelaChat {',
    '  try { if ($global:ChatPowerShell) { $global:ChatPowerShell.Stop() } } catch {}',
    '  try { if ($global:ChatRunspace) { $global:ChatRunspace.Close() } } catch {}',
    '  Start-Sleep -Milliseconds 400',
    '}',
    '',
    'function Verificar-Atualizacao {',
    '  try {',
    '    $respVersao = Invoke-RestMethod -Uri $UrlVersao -Method Get -TimeoutSec 10',
    '    if ($respVersao -and $respVersao.versao -and ([int]$respVersao.versao -gt $VersaoScript)) {',
    '      Escrever-Log "Versao nova disponivel ($($respVersao.versao), essa copia e $VersaoScript) - baixando..."',
    '      $novoConteudo = Invoke-RestMethod -Uri $UrlScriptProprio -Method Get -Headers $CabecalhosAgente -TimeoutSec 30',
    '      if ($novoConteudo -and ($novoConteudo -is [string]) -and $novoConteudo.StartsWith("# NOCZenith")) {',
    '        Set-Content -Path $PSCommandPath -Value $novoConteudo -Encoding UTF8 -Force',
    '        Escrever-Log "Atualizado para versao $($respVersao.versao) - reiniciando."',
    '        # a instancia de boot renasce COMO instancia de boot - sem repassar o',
    '        # -Servico, a copia nova se acharia a de login e as duas iam trabalhar',
    '        # juntas (heartbeat dobrado, comando executado duas vezes)',
    '        $argsNovo = "-WindowStyle Hidden -ExecutionPolicy Bypass -File `"$PSCommandPath`" -Loop"',
    '        if ($Servico) { $argsNovo += " -Servico" }',
    '        Start-Process powershell.exe -ArgumentList $argsNovo',
    '        Start-Sleep -Seconds 2',
    '        Encerrar-JanelaChat',
    '        exit',
    '      } else {',
    '        Escrever-Log "Conteudo novo baixado nao parece valido - mantendo versao atual."',
    '      }',
    '    }',
    '  } catch {',
    '    Escrever-Log "Falha ao verificar atualizacao: $($_.Exception.Message)"',
    '  }',
    '}',
    '',
  ];

  // Cede a vez entre as instancias de boot e de login - mesmo trecho nos
  // dois tipos de loop, no TOPO de cada volta. A de boot em espera continua
  // acordando a cada tick, so nao faz nada (nem heartbeat, nem comando).
  const linhasCedencia = [
    '    if (-not $Servico) { Marcar-UiAtiva }',
    '    elseif (UiEstaAtiva) {',
    '      if (-not $EmEsperaServico) { Escrever-Log "Instancia de login ativa - a de boot fica em espera."; $EmEsperaServico = $true }',
    '      Start-Sleep -Seconds $IntervaloSegundos',
    '      continue',
    '    }',
    '    elseif ($EmEsperaServico) { Escrever-Log "Instancia de login parou - a de boot reassume."; $EmEsperaServico = $false }',
  ];

  const linhasLoopInterno = [
    '$UrlHeartbeat = "' + urlHeartbeat + '"',
    '$UrlComandoResultado = "' + urlComandoResultado + '"',
    '$UrlChatResponder = "' + urlChatResponder + '"',
    '$UrlReportarIp = "' + urlReportarIp + '"',
    '$IntervaloSegundos = 25',
    '# a cada ~144 ticks de 25s (~1h) confere se tem versao nova',
    '$TicksParaVerificarAtualizacao = 144',
    '# a cada ~12 ticks de 25s (~5min) mede a rede (ping no roteador e na',
    '# internet). Espacado de proposito: o teste custa alguns segundos e o',
    '# que nao pode atrasar e o heartbeat.',
    '$TicksParaDiagnosticoRede = 12',
    '# saude do HD a cada ~864 ticks de 25s (~6h) e varredura da rede local a',
    '# cada ~144 (~1h). Disco nao muda de estado em minutos e a lista de',
    '# aparelhos da loja tambem nao - medir mais nao informa mais, so gera',
    '# escrita. As duas tambem rodam uma vez logo apos o boot (tick 4), senao',
    '# o painel ficaria 6h vazio depois de cada reinicio.',
    '$TicksParaDisco = 864',
    '$TicksParaVarreduraRede = 144',
    '# a sonda da impressora e o que derruba a deteccao de ~2h pra minutos:',
    '# 4 ticks x 25s = ~100s. So abre socket se a lista nao estiver vazia.',
    '$TicksParaSondarImpressora = 4',
    '# link fisico a cada ~4 ticks de 25s (~100s). Nao vale medir a cada',
    '# batida: e uma consulta ao Windows e o cabo nao cai e volta em 25s. E',
    '# nao vale espacar mais: e o dado que diz se a loja caiu pro Wi-Fi.',
    '$TicksParaLink = 4',
    '$Link = $null',
    '# medicao de link acumulada entre uma volta e outra (ver',
    '# redeDiagnostico.js no servidor). A latencia do heartbeat so fica',
    '# conhecida DEPOIS que ele responde, entao cada beat leva a medida do',
    '# beat anterior - de todo jeito o servidor so quer a serie, nao o',
    '# instante exato.',
    '$UltimaLatenciaMs = $null',
    '$DiagRede = @{}',
    '',
    '# ---- janela de chat flutuante (estilo Splashtop) - roda numa thread',
    '# STA propria (runspace dedicado com sua propria mensagem de janela),',
    '# pra nunca travar o loop principal de heartbeat esperando alguem',
    '# interagir com a janela. A ponte entre as duas threads e por fila',
    '# sincronizada: FilaChatEntrada leva mensagem nova do Master pra',
    '# aparecer na janela; FilaChatSaida leva o que a pessoa digitou de',
    '# volta pro loop principal, que manda pro servidor. Qualquer falha aqui',
    '# (por exemplo, maquina sem sessao grafica) fica presa no try/catch e',
    '# nunca derruba o monitoramento - so fica sem a janela.',
    '$global:FilaChatEntrada = [System.Collections.Queue]::Synchronized((New-Object System.Collections.Queue))',
    '$global:FilaChatSaida = [System.Collections.Queue]::Synchronized((New-Object System.Collections.Queue))',
    '',
    'function Iniciar-JanelaChat {',
    '  $rs = [runspacefactory]::CreateRunspace()',
    '  $rs.ApartmentState = "STA"',
    '  $rs.ThreadOptions = "ReuseThread"',
    '  $rs.Open()',
    '  $rs.SessionStateProxy.SetVariable("FilaChatEntrada", $global:FilaChatEntrada)',
    '  $rs.SessionStateProxy.SetVariable("FilaChatSaida", $global:FilaChatSaida)',
    '  $rs.SessionStateProxy.SetVariable("TituloJanelaChat", "NoPulso - ' + codigoTextoPS + ' / ' + posto + '")',
    '  # passa o caminho do log pra DENTRO da thread da janela - sem isso, se o',
    '  # WinForms falhar (maquina sem sessao grafica, .NET incompleto), a janela',
    '  # morria em silencio total e nao dava pra saber por que o chat nao abria',
    '  $rs.SessionStateProxy.SetVariable("CaminhoLogChat", $CaminhoLog)',
    '  $ps = [powershell]::Create()',
    '  $ps.Runspace = $rs',
    '  [void]$ps.AddScript({',
    '    function Log-Chat($m) { try { "$([DateTime]::Now.ToString(\'yyyy-MM-dd HH:mm:ss\')) - [janela] $m" | Out-File -FilePath $CaminhoLogChat -Append -Encoding UTF8 } catch {} }',
    '    try {',
    '    Add-Type -AssemblyName System.Windows.Forms',
    '    Add-Type -AssemblyName System.Drawing',
    '',
    '    # TRAVA DE SEGURANCA DA LOJA - nada nesta thread pode virar caixa de',
    '    # dialogo na tela do PDV. Sem isso, qualquer excecao aqui dentro sobe',
    '    # ate o WinForms e ele abre o "Ocorreu uma excecao sem tratamento no',
    '    # aplicativo", modal e por cima do sistema da loja, esperando alguem',
    '    # clicar. Foi o que aconteceu em TODAS as lojas ao atualizar o vigia:',
    '    # o processo antigo saía (exit) e o Tick de 1s seguinte era invocado',
    '    # num runspace ja morto -> PipelineStoppedException -> dialogo.',
    '    # SetUnhandledExceptionMode tem que vir ANTES de criar qualquer janela',
    '    # nesta thread, senao nao vale.',
    '    [System.Windows.Forms.Application]::SetUnhandledExceptionMode([System.Windows.Forms.UnhandledExceptionMode]::CatchException)',
    '    [System.Windows.Forms.Application]::add_ThreadException({',
    '      param($origemErro, $argsErro)',
    '      try { Log-Chat "Excecao na thread da janela (engolida de proposito): $($argsErro.Exception.Message)" } catch {}',
    '    })',
    '',
    '    $form = New-Object System.Windows.Forms.Form',
    '    $form.Text = $TituloJanelaChat',
    '    $form.Size = New-Object System.Drawing.Size(340, 420)',
    '    $form.FormBorderStyle = "FixedSingle"',
    '    $form.MaximizeBox = $false',
    '    $form.ShowInTaskbar = $false',
    '    $form.TopMost = $true',
    '    $form.StartPosition = "Manual"',
    '    $area = [System.Windows.Forms.Screen]::PrimaryScreen.WorkingArea',
    '    $form.Location = New-Object System.Drawing.Point(($area.Width - 360), ($area.Height - 440))',
    '',
    '    $cabecalho = New-Object System.Windows.Forms.Panel',
    '    $cabecalho.Dock = "Top"',
    '    $cabecalho.Height = 40',
    '    $cabecalho.BackColor = [System.Drawing.Color]::FromArgb(0, 120, 215)',
    '    $lblCabecalho = New-Object System.Windows.Forms.Label',
    '    $lblCabecalho.Text = "Suporte NoPulso"',
    '    $lblCabecalho.ForeColor = [System.Drawing.Color]::White',
    '    $lblCabecalho.Font = New-Object System.Drawing.Font("Segoe UI", 11, [System.Drawing.FontStyle]::Bold)',
    '    $lblCabecalho.Dock = "Fill"',
    '    $lblCabecalho.TextAlign = "MiddleLeft"',
    '    $lblCabecalho.Padding = New-Object System.Windows.Forms.Padding(10, 0, 0, 0)',
    '    $cabecalho.Controls.Add($lblCabecalho)',
    '',
    '    $historico = New-Object System.Windows.Forms.RichTextBox',
    '    $historico.Dock = "Fill"',
    '    $historico.ReadOnly = $true',
    '    $historico.BackColor = [System.Drawing.Color]::FromArgb(245, 247, 250)',
    '    $historico.BorderStyle = "None"',
    '    $historico.Font = New-Object System.Drawing.Font("Segoe UI", 9)',
    '',
    '    $rodape = New-Object System.Windows.Forms.Panel',
    '    $rodape.Dock = "Bottom"',
    '    $rodape.Height = 44',
    '    $rodape.Padding = New-Object System.Windows.Forms.Padding(6)',
    '',
    '    $txtEntrada = New-Object System.Windows.Forms.TextBox',
    '    $txtEntrada.Dock = "Fill"',
    '    $txtEntrada.Font = New-Object System.Drawing.Font("Segoe UI", 9)',
    '',
    '    $btnEnviar = New-Object System.Windows.Forms.Button',
    '    $btnEnviar.Text = "Enviar"',
    '    $btnEnviar.Dock = "Right"',
    '    $btnEnviar.Width = 68',
    '    $btnEnviar.BackColor = [System.Drawing.Color]::FromArgb(0, 120, 215)',
    '    $btnEnviar.ForeColor = [System.Drawing.Color]::White',
    '    $btnEnviar.FlatStyle = "Flat"',
    '',
    '    $EnviarTexto = {',
    '      $texto = $txtEntrada.Text.Trim()',
    '      if ($texto) {',
    '        $historico.SelectionColor = [System.Drawing.Color]::FromArgb(0, 120, 215)',
    '        $historico.AppendText([Environment]::NewLine + "[$(Get-Date -Format "HH:mm")] Voce: ")',
    '        $historico.SelectionColor = [System.Drawing.Color]::Black',
    '        $historico.AppendText($texto)',
    '        $historico.ScrollToCaret()',
    '        $FilaChatSaida.Enqueue($texto)',
    '        $txtEntrada.Text = ""',
    '      }',
    '    }',
    '    $btnEnviar.Add_Click($EnviarTexto)',
    '    $txtEntrada.Add_KeyDown({',
    '      param($origemEvento, $evento)',
    '      if ($evento.KeyCode -eq "Enter") { & $EnviarTexto; $evento.SuppressKeyPress = $true }',
    '    })',
    '',
    '    $rodape.Controls.Add($txtEntrada)',
    '    $rodape.Controls.Add($btnEnviar)',
    '',
    '    $form.Controls.Add($historico)',
    '    $form.Controls.Add($rodape)',
    '    $form.Controls.Add($cabecalho)',
    '',
    '    $timer = New-Object System.Windows.Forms.Timer',
    '    $timer.Interval = 1000',
    '    $timer.Add_Tick({',
    '      # try/catch aqui dentro tambem: o Tick roda como delegate do',
    '      # WinForms, entao e o ponto mais provavel de estourar quando algo',
    '      # ao redor morre (runspace fechado, fila sumindo)',
    '      try {',
    '      while ($FilaChatEntrada.Count -gt 0) {',
    '        $msg = $FilaChatEntrada.Dequeue()',
    '        $historico.SelectionColor = [System.Drawing.Color]::FromArgb(130, 130, 130)',
    '        $historico.AppendText([Environment]::NewLine + "[$(Get-Date -Format "HH:mm")] Suporte: ")',
    '        $historico.SelectionColor = [System.Drawing.Color]::FromArgb(30, 30, 30)',
    '        $historico.AppendText($msg)',
    '        $historico.ScrollToCaret()',
    '        if (-not $form.Visible) { $form.Show() }',
    '        $form.WindowState = "Normal"',
    '        $form.Activate()',
    '      }',
    '      } catch { try { Log-Chat "Falha no tick da janela: $($_.Exception.Message)" } catch {} }',
    '    })',
    '    $timer.Start()',
    '',
    '    $form.Add_FormClosing({',
    '      param($origemEvento, $evento)',
    '      $evento.Cancel = $true',
    '      $form.Hide()',
    '    })',
    '',
    '    Log-Chat "Janela de chat pronta."',
    '    [System.Windows.Forms.Application]::Run()',
    '    } catch { Log-Chat "ERRO ao montar a janela: $($_.Exception.Message)" }',
    '  })',
    '  [void]$ps.BeginInvoke()',
    '  $global:ChatRunspace = $rs',
    '  $global:ChatPowerShell = $ps',
    '}',
    '',
    '# reporta o IP da rede LOCAL pro NOC (aparece no card do computador). Na',
    '# largada (reaparece logo apos reinicio/atualizacao) e a cada ~6 ticks.',
    'function Reportar-IpLocal {',
    '  try {',
    '    $ip = (Get-NetIPAddress -AddressFamily IPv4 -AddressState Preferred -ErrorAction SilentlyContinue |',
    '      Where-Object { $_.IPAddress -notlike "127.*" -and $_.IPAddress -notlike "169.254.*" } |',
    '      Select-Object -First 1 -ExpandProperty IPAddress)',
    '    if ($ip) { Invoke-RestMethod -Uri $UrlReportarIp -Method Post -ContentType "application/json" -Headers $CabecalhosAgente -Body (@{ ip = $ip } | ConvertTo-Json) -TimeoutSec 10 | Out-Null }',
    '  } catch { Escrever-Log "Falha ao reportar IP local: $($_.Exception.Message)" }',
    '}',
    '',
    '# ---- diagnostico de link -------------------------------------------',
    '# Mede DOIS saltos separados, e essa separacao e o ponto todo: o ping ate',
    '# o roteador da loja mostra a rede interna (cabo/switch/wifi) e o ping ate',
    '# a internet mostra o link da operadora. Com os dois da pra dizer com quem',
    '# reclamar, em vez de so "a internet ta ruim".',
    '# -Count 2 de proposito: Test-Connection nao tem timeout no PS 5.1 e cada',
    '# ping que falha segura ~4s. Com 2+2 o pior caso fica ~16s, bem abaixo do',
    '# limiar de 90s do NOC mesmo somando com o heartbeat.',
    'function Medir-Ping($alvo) {',
    '  $r = @{ ms = $null; perda = $null }',
    '  if (-not $alvo) { return $r }',
    '  try {',
    '    $envios = 2',
    '    $res = @(Test-Connection -ComputerName $alvo -Count $envios -ErrorAction SilentlyContinue)',
    '    $ok = @($res | Where-Object { $_ -ne $null })',
    '    $r.perda = [int]((($envios - $ok.Count) / $envios) * 100)',
    '    if ($ok.Count -gt 0) {',
    '      $r.ms = [int](($ok | Measure-Object -Property ResponseTime -Average).Average)',
    '    }',
    '  } catch {}',
    '  return $r',
    '}',
    '',
    'function Medir-Rede {',
    '  $d = @{}',
    '  try {',
    '    # gateway padrao = o roteador por onde a loja sai pra internet',
    '    $gw = (Get-NetRoute -DestinationPrefix "0.0.0.0/0" -ErrorAction SilentlyContinue |',
    '      Sort-Object RouteMetric | Select-Object -First 1 -ExpandProperty NextHop)',
    '    $pGw = Medir-Ping $gw',
    '    $d.gatewayMs = $pGw.ms',
    '    $d.gatewayPerdaPct = $pGw.perda',
    '    $pWan = Medir-Ping "8.8.8.8"',
    '    $d.wanMs = $pWan.ms',
    '    $d.wanPerdaPct = $pWan.perda',
    '    # cabo x wifi muda completamente o que fazer com um link ruim, entao',
    '    # vale identificar - e no wifi o sinal costuma ser a causa direta',
    '    $ad = (Get-NetAdapter -Physical -ErrorAction SilentlyContinue |',
    '      Where-Object { $_.Status -eq "Up" } | Select-Object -First 1)',
    '    if ($ad) {',
    '      $ehWifi = ($ad.InterfaceDescription -match "Wireless|Wi-?Fi|WLAN") -or ($ad.MediaType -eq "Native 802.11")',
    '      $d.conexao = if ($ehWifi) { "wifi" } else { "cabo" }',
    '      if ($ehWifi) {',
    '        # netsh e traduzido conforme o Windows, entao nao da pra casar o',
    '        # rotulo ("Signal"/"Sinal"). Pega a linha que termina em N% -',
    '        # unico percentual da saida de "show interfaces"',
    '        $linhas = (netsh wlan show interfaces) 2>$null',
    '        foreach ($l in $linhas) {',
    '          if ($l -match ":\\s*(\\d{1,3})%\\s*$") { $d.sinalWifi = [int]$matches[1]; break }',
    '        }',
    '      }',
    '    }',
    '  } catch { Escrever-Log "Falha ao medir rede: $($_.Exception.Message)" }',
    '  return $d',
    '}',
    '',
    // ---- a outra causa de silencio, e essa e culpa NOSSA ----
    // As auxiliares (varredura ARP, sonda de impressora, telemetria, comando
    // do Master, medicao de rede) rodam DEPOIS do heartbeat, mas comem tempo
    // do mesmo tick - e o sleep de 25s vem inteiro por cima. Um tick pesado
    // (ARP ~12s + sonda de ate 4s por impressora + POST de telemetria ate
    // 15s) empurra a proxima batida pra perto dos 90s do NOC, e a maquina
    // aparece "indisponivel" sem nunca ter parado. Uma batida MINIMA (so
    // presenca) custa nada e fecha o buraco.
    // Nao leva rede/link/boot de proposito: essas medidas tem dono no beat
    // normal, e mandar vazio aqui atrapalharia a leitura seguinte. O servidor
    // preenche o resto do documento com o que ja tinha (merge).
    '$UltimoBeatOkEm = $null',
    'function Bater-Rapido {',
    '  try {',
    '    $c = @{ unidade = "' + codigoTextoPS + '"; posto = "' + posto + '"; userAgent = "NOCZenith/1.0 (Windows NT; PowerShell)" } | ConvertTo-Json',
    '    Invoke-RestMethod -Uri $UrlHeartbeat -Method Post -ContentType "application/json" -Headers $CabecalhosAgente -Body $c -TimeoutSec 10 | Out-Null',
    '    $script:UltimoBeatOkEm = [DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()',
    '  } catch {}',
    '}',
    '# quanto tempo o tick pode ter comido antes de valer a pena bater de novo.',
    '# 45s = metade do limiar de 90s do NOC: sobra folga pra proxima batida',
    '# normal atrasar tambem sem a maquina piscar no painel.',
    '$LimiteTickMs = 45000',
    '',
    'function Rodar-Loop {',
    '  Escrever-Log "NOCZenith iniciado (interno$(if ($Servico) { ", instancia de boot" })) - versao $VersaoScript - ' + codigoTextoPS + '/' + posto + '"',
    '  Reportar-IpLocal',
    '  # a instancia de boot roda como SYSTEM, sem sessao grafica - janela de',
    '  # chat so na instancia de login',
    '  if (-not $Servico) { try { Iniciar-JanelaChat } catch { Escrever-Log "Falha ao abrir janela de chat: $($_.Exception.Message)" } }',
    '  $EmEsperaServico = $false',
    '  $contador = 0',
    '  $FalhasSeguidasHeartbeat = 0',
    '  $TicksFalhandoHeartbeat = 0',
    '  # baseline do chat vem do TIMESTAMP DO SERVIDOR (em), nao do relogio',
    '  # local - antes usava a hora local do PC, e se o computador estava',
    '  # atrasado (comum), toda mensagem do Master tinha em < hora local e',
    '  # era descartada: a janela NUNCA abria. Agora os dois lados usam a mesma',
    '  # referencia (o em do servidor), entao independe do relogio da maquina',
    '  $UltimoChatEm = -1',
    '  $ChatBaselineFeito = $false',
    '  while ($true) {',
    ...linhasCedencia,
    '    $resp = $null',
    '    $tentativa = 0',
    '    try {',
    // O bloco `rede` viaja junto no heartbeat que ja existe - o servidor
    // grava tudo na mesma escrita do Firestore, entao a telemetria de link
    // nao custa uma operacao a mais (ver redeDiagnostico.js).
    '      $rede = @{ falhasSeguidas = $FalhasSeguidasHeartbeat }',
    '      if ($UltimaLatenciaMs -ne $null) { $rede.latenciaMs = $UltimaLatenciaMs }',
    '      foreach ($k in $DiagRede.Keys) { if ($DiagRede[$k] -ne $null) { $rede[$k] = $DiagRede[$k] } }',
    '      # zera os dois DEPOIS de montar o corpo: cada medicao tem que ser',
    '      # enviada uma vez so. Se continuassem valendo, o mesmo ping ia junto',
    '      # nos 12 beats seguintes e pesaria 12x na media do dia.',
    '      $UltimaLatenciaMs = $null',
    '      $DiagRede = @{}',
    '      $corpo = @{ unidade = "' + codigoTextoPS + '"; posto = "' + posto + '"; userAgent = "NOCZenith/1.0 (Windows NT; PowerShell)"; abertoDesde = $InicioScript; rede = $rede }',
    '      # boot vai em TODA batida (e uma variavel ja lida, custo zero) - e o',
    '      # que deixa o servidor separar "reiniciou" de "so caiu a rede"',
    '      if ($BootEm -ne $null) { $corpo.bootEm = $BootEm; $corpo.desligamentoInesperado = $DesligamentoInesperado }',
    '      if ($Link -ne $null) { $corpo.link = $Link }',
    '      if ($AnyDeskSvc -ne $null) { $corpo.anydeskServico = $AnyDeskSvc }',
    '      $corpo = $corpo | ConvertTo-Json -Depth 4',
    '      $cronometro = [Diagnostics.Stopwatch]::StartNew()',
    // UMA batida perdida virava 25s de silencio, e o NOC corta em 90s: tres
    // engasgos seguidos ja pintavam a loja de vermelho, e ~9 (pouco mais de
    // 4min) disparavam o alarme sonoro numa maquina que nunca desligou. Um
    // engasgo de rede de poucos segundos e o caso COMUM - fibra renegociando,
    // DNS lento, o Render acordando. Entao a batida insiste dentro do proprio
    // tick, em vez de largar e esperar o proximo: 3 tentativas com 4s e 8s de
    // intervalo. So se as tres falharem o tick conta como falha - e ai e
    // silencio de verdade, que tem que aparecer mesmo.
    '      $entregue = $false',
    '      $tentativa = 0',
    '      $erroBeat = $null',
    '      while ($tentativa -lt 3 -and -not $entregue) {',
    '        $tentativa++',
    '        if ($tentativa -gt 1) { Start-Sleep -Seconds (4 * ($tentativa - 1)) }',
    '        try {',
    '          $resp = Invoke-RestMethod -Uri $UrlHeartbeat -Method Post -ContentType "application/json" -Headers $CabecalhosAgente -Body $corpo -TimeoutSec 10',
    '          $entregue = $true',
    '        } catch { $erroBeat = $_ }',
    '      }',
    // relanca pro catch de fora - a contabilidade de falha e o log continuam
    // num lugar so, e o erro que sobe e o da ULTIMA tentativa
    '      if (-not $entregue) { throw $erroBeat }',
    '      $cronometro.Stop()',
    '      $script:UltimoBeatOkEm = [DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()',
    '      # latencia real de ponta a ponta do jeito que o sistema e usado -',
    '      # vai no PROXIMO beat, ja que so fica conhecida agora',
    '      $UltimaLatenciaMs = [int]$cronometro.ElapsedMilliseconds',
    '      if ($FalhasSeguidasHeartbeat -gt 0) { Escrever-Log "Heartbeat voltou a funcionar (depois de $FalhasSeguidasHeartbeat tentativa(s) seguidas sem passar)." }',
    '      $FalhasSeguidasHeartbeat = 0',
    '      $TicksFalhandoHeartbeat = 0',
    '    } catch {',
    // conta TENTATIVAS, nao ticks: o numero viaja pro servidor (rede.
    // falhasSeguidas) e e o que prova, na volta, que a maquina esteve viva
    // batendo na porta o silencio inteiro
    '      $FalhasSeguidasHeartbeat += [Math]::Max(1, $tentativa)',
    // dois contadores porque medem coisas diferentes: TENTATIVAS e o que vai
    // pro servidor (e o que prova, na volta, que a maquina esteve viva
    // batendo na porta); TICKS e o que decide o log. Com 3 tentativas por
    // tick, "primeira falha" nunca mais seria 1 no contador de tentativas -
    // e a linha de log que diz A CAUSA (DNS? timeout? 502?) desapareceria
    // justo no caso que ela existe pra explicar.
    '      $TicksFalhandoHeartbeat++',
    '      # so loga o 1o tick que falha e depois 1 a cada ~40 (~45min, ja que',
    '      # o tick com as 3 tentativas fica mais longo) - senao uma internet',
    '      # caida por horas enche o log de linhas repetidas',
    '      if ($TicksFalhandoHeartbeat -eq 1 -or ($TicksFalhandoHeartbeat % 40 -eq 0)) {',
    '        Escrever-Log "Falha no heartbeat ($tentativa tentativa(s) neste tick, $FalhasSeguidasHeartbeat seguidas): $($_.Exception.Message)"',
    '      }',
    '    }',
    '    if ($resp) {',
    '      if ($resp.comandoPendente) {',
    '        Escrever-Log "Comando recebido (id=$($resp.comandoPendente.comandoId))"',
    '        try {',
    '          $sb = [scriptblock]::Create($resp.comandoPendente.comando)',
    '          $saidaComando = (& $sb 2>&1 | Out-String)',
    '          $corpoOk = @{ comandoId = $resp.comandoPendente.comandoId; resultado = $saidaComando } | ConvertTo-Json',
    '          Invoke-RestMethod -Uri $UrlComandoResultado -Method Post -ContentType "application/json" -Headers $CabecalhosAgente -Body $corpoOk -TimeoutSec 10 -ErrorAction SilentlyContinue | Out-Null',
    '          Escrever-Log "Comando executado (id=$($resp.comandoPendente.comandoId))"',
    '        } catch {',
    '          Escrever-Log "Comando falhou (id=$($resp.comandoPendente.comandoId)): $($_.Exception.Message)"',
    '          try {',
    '            $corpoErro = @{ comandoId = $resp.comandoPendente.comandoId; erro = $_.Exception.Message } | ConvertTo-Json',
    '            Invoke-RestMethod -Uri $UrlComandoResultado -Method Post -ContentType "application/json" -Headers $CabecalhosAgente -Body $corpoErro -TimeoutSec 10 -ErrorAction SilentlyContinue | Out-Null',
    '          } catch {}',
    '        }',
    '      }',
    '      # 1o ciclo: so marca o que ja existe como "visto" (nao repopa o',
    '      # historico), usando o em do servidor como baseline. Dai em diante,',
    '      # so mensagens do Master com em MAIOR que esse baseline abrem a janela',
    '      if (-not $ChatBaselineFeito) {',
    '        foreach ($m in $resp.chatMensagens) { if ($m.em -gt $UltimoChatEm) { $UltimoChatEm = $m.em } }',
    '        $ChatBaselineFeito = $true',
    '        Escrever-Log "Chat pronto (baseline em=$UltimoChatEm, $($resp.chatMensagens.Count) msg no historico)."',
    '      } else {',
    '        foreach ($m in $resp.chatMensagens) {',
    '          if ($m.de -eq "master" -and $m.em -gt $UltimoChatEm) {',
    '            Escrever-Log "Mensagem recebida do Master - abrindo janela."',
    '            try { $global:FilaChatEntrada.Enqueue([string]$m.texto) } catch { Escrever-Log "Falha ao enfileirar msg pra janela: $($_.Exception.Message)" }',
    '          }',
    '          if ($m.em -gt $UltimoChatEm) { $UltimoChatEm = $m.em }',
    '        }',
    '      }',
    '    }',
    '    try {',
    '      while ($global:FilaChatSaida.Count -gt 0) {',
    '        $textoParaEnviar = $global:FilaChatSaida.Dequeue()',
    '        $corpoChat = @{ texto = $textoParaEnviar } | ConvertTo-Json',
    '        Invoke-RestMethod -Uri $UrlChatResponder -Method Post -ContentType "application/json" -Headers $CabecalhosAgente -Body $corpoChat -TimeoutSec 10 | Out-Null',
    '        Escrever-Log "Resposta enviada pela janela de chat."',
    '      }',
    '    } catch {',
    '      Escrever-Log "Falha ao enviar resposta do chat: $($_.Exception.Message)"',
    '    }',
    '    # AUXILIARES so quando o heartbeat passou. Com a rede engasgada, cada',
    '    # chamada extra so empilha atraso em cima do proximo heartbeat - e o',
    '    # heartbeat e a unica coisa que nao pode atrasar (limiar de 90s no NOC).',
    '    if ($resp) {',
    '      try { Verificar-AcessoRemoto } catch { Escrever-Log "Falha ao checar acesso remoto: $($_.Exception.Message)" }',
    '    }',
    '    $contador++',
    '    # o resultado fica guardado em $DiagRede e viaja no PROXIMO heartbeat',
    '    if ($resp -and $contador % $TicksParaDiagnosticoRede -eq 0) {',
    '      try { $DiagRede = Medir-Rede } catch { Escrever-Log "Falha no diagnostico de rede: $($_.Exception.Message)" }',
    '    }',
    '    if ($resp -and $contador % 6 -eq 0) { Reportar-IpLocal }',
    '    # medido ANTES do proximo heartbeat, entao viaja na batida seguinte',
    '    # o AnyDesk vai na mesma cadencia do link: os dois sao leitura barata',
    '    # do que o Windows ja sabe, e viajam na batida seguinte',
    '    if ($contador -eq 1 -or $contador % $TicksParaLink -eq 0) {',
    '      try { $AnyDeskSvc = Medir-AnyDesk } catch { $AnyDeskSvc = $null }',
    '      try { $Link = Medir-Link } catch { Escrever-Log "Falha ao medir o link: $($_.Exception.Message)" }',
    '    }',
    '    # saude do HD + varredura da rede local (ver nocMaquina.js). Vao numa',
    '    # chamada so quando caem no mesmo tick, pra nao bater duas vezes',
    '    if ($resp) {',
    '      $discoAgora = $null; $redeAgora = $null',
    '      if ($contador -eq 4 -or $contador % $TicksParaDisco -eq 0) { $discoAgora = Medir-Disco }',
    '      if ($contador -eq 4 -or $contador % $TicksParaVarreduraRede -eq 0) { $redeAgora = Varrer-RedeLocal }',
    '      $impAgora = $null',
    '      if ($contador % $TicksParaSondarImpressora -eq 0) { $impAgora = Sondar-Impressoras }',
    '      if ($discoAgora -or $redeAgora -or $impAgora) { Enviar-Telemetria $discoAgora $redeAgora $impAgora }',
    '    }',
    '    if ($resp -and $contador % $TicksParaVerificarAtualizacao -eq 0) { Verificar-Atualizacao }',
    '    # tick pesado nao pode virar queda falsa (ver Bater-Rapido)',
    '    if ($script:UltimoBeatOkEm -ne $null -and (([DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds() - $script:UltimoBeatOkEm) -gt $LimiteTickMs)) { Bater-Rapido }',
    '    Start-Sleep -Seconds $IntervaloSegundos',
    '  }',
    '}',
    '',
  ];

  const linhasLoopOutros = [
    '$TituloJanela = "NoPulso"',
    '$UrlMonitorar = "' + urlMonitorar + '"',
    '$UrlReportarIp = "' + urlReportarIp + '"',
    '$IntervaloSegundos = 20',
    // a checagem de acesso remoto roda TODO tick (20s); reabrir a janela e
    // reportar o IP local continuam no ritmo de antes (120s = 6 ticks) - so
    // trocou o "relogio" do loop pra dar mais rapidez no alerta de acesso
    // remoto sem mudar a frequencia das outras duas tarefas
    '$TicksParaVerificacaoPesada = 6',
    '# a cada ~180 ticks de 20s (~1h) confere se tem versao nova',
    '$TicksParaVerificarAtualizacao = 180',
    '# mesmas cadencias do tipo interno (~6h disco, ~1h rede), convertidas pro',
    '# tick de 20s deste loop',
    '$TicksParaDisco = 1080',
    '$TicksParaVarreduraRede = 180',
    '# ~100s tambem aqui (5 ticks x 20s)',
    '$TicksParaSondarImpressora = 5',
    '',
    'function Reabrir-Monitor {',
    '  $candidatos = @(',
    '    "$env:ProgramFiles\\Google\\Chrome\\Application\\chrome.exe",',
    '    "${env:ProgramFiles(x86)}\\Google\\Chrome\\Application\\chrome.exe",',
    '    "$env:ProgramFiles\\Microsoft\\Edge\\Application\\msedge.exe",',
    '    "${env:ProgramFiles(x86)}\\Microsoft\\Edge\\Application\\msedge.exe"',
    '  )',
    '  $navegador = $candidatos | Where-Object { Test-Path $_ } | Select-Object -First 1',
    '  if ($navegador) {',
    '    Start-Process -FilePath $navegador -ArgumentList "--app=$UrlMonitorar" -WindowStyle Minimized',
    '  } else {',
    '    Start-Process $UrlMonitorar',
    '  }',
    '}',
    '',
    '# reporta o IP local da maquina (rede da loja) pro NOC. Chamado na largada',
    '# (pra reaparecer logo apos qualquer reinicio/atualizacao do vigia) e a',
    '# cada tick pesado.',
    'function Reportar-IpLocal {',
    '  try {',
    '    $ip = (Get-NetIPAddress -AddressFamily IPv4 -AddressState Preferred -ErrorAction SilentlyContinue |',
    '      Where-Object { $_.IPAddress -notlike "127.*" -and $_.IPAddress -notlike "169.254.*" } |',
    '      Select-Object -First 1 -ExpandProperty IPAddress)',
    '    if ($ip) {',
    '      Invoke-RestMethod -Uri $UrlReportarIp -Method Post -ContentType "application/json" -Headers $CabecalhosAgente -Body (@{ ip = $ip } | ConvertTo-Json) -TimeoutSec 10 | Out-Null',
    '    }',
    '  } catch { Escrever-Log "Falha ao reportar IP local: $($_.Exception.Message)" }',
    '}',
    '',
    'function Rodar-Loop {',
    '  Escrever-Log "NOCZenith iniciado (' + tipo + '$(if ($Servico) { ", instancia de boot" })) - versao $VersaoScript - ' + codigoTextoPS + '/' + posto + '"',
    '  Reportar-IpLocal',
    '  $EmEsperaServico = $false',
    '  $contador = 0',
    '  while ($true) {',
    ...linhasCedencia,
    // Aqui NAO tem guarda de heartbeat como no loop interno: neste tipo quem
    // bate o heartbeat e a pagina aberta no navegador, nao o PowerShell. Nao
    // existe $resp - guardar por ele deixaria tudo abaixo morto pra sempre,
    // inclusive o auto-update.
    '    try { Verificar-AcessoRemoto } catch { Escrever-Log "Falha ao checar acesso remoto: $($_.Exception.Message)" }',
    '    $contador++',
    '    if ($contador % $TicksParaVerificacaoPesada -eq 0) {',
    '      # a instancia de boot (SYSTEM) nao gerencia janela: abrir navegador',
    '      # sem sessao grafica so acumularia processo fantasma na sessao 0',
    '      if (-not $Servico) {',
    '        $aberto = Get-Process | Where-Object { $_.MainWindowTitle -match [regex]::Escape($TituloJanela) } | Select-Object -First 1',
    '        if (-not $aberto) { Escrever-Log "Tela de monitoramento fechada - reabrindo."; Reabrir-Monitor }',
    '      }',
    '      Reportar-IpLocal',
    '    }',
    '    # saude do HD + varredura da rede local (ver nocMaquina.js) - aqui vale',
    '    # igual: quem bate o heartbeat e o navegador, mas a telemetria e do',
    '    # agente, entao ela funciona nos dois tipos de computador',
    '    $discoAgora = $null; $redeAgora = $null',
    '    if ($contador -eq 5 -or $contador % $TicksParaDisco -eq 0) { $discoAgora = Medir-Disco }',
    '    if ($contador -eq 5 -or $contador % $TicksParaVarreduraRede -eq 0) { $redeAgora = Varrer-RedeLocal }',
    '    $impAgora = $null',
    '    if ($contador % $TicksParaSondarImpressora -eq 0) { $impAgora = Sondar-Impressoras }',
    '    if ($discoAgora -or $redeAgora -or $impAgora) { Enviar-Telemetria $discoAgora $redeAgora $impAgora }',
    '    if ($contador % $TicksParaVerificarAtualizacao -eq 0) { Verificar-Atualizacao }',
    '    Start-Sleep -Seconds $IntervaloSegundos',
    '  }',
    '}',
    '',
  ];

  const linhasFinal = [
    'if ($Loop) {',
    '  Rodar-Loop',
    '} else {',
    '  # instala numa pasta fixa e protegida (%LOCALAPPDATA%\\NOCZenith): assim o',
    '  # arquivo baixado pode ser apagado e o agendamento nunca aponta pra um',
    '  # caminho que alguem vai mover/limpar (ex: Downloads). Se ja estiver',
    '  # rodando dessa pasta (reinstalacao), nao copia de novo.',
    '  $PastaFixa = Join-Path $env:LOCALAPPDATA "NOCZenith"',
    '  $Destino = Join-Path $PastaFixa "NOCZenith.ps1"',
    '  try {',
    '    if (-not (Test-Path $PastaFixa)) { New-Item -ItemType Directory -Path $PastaFixa -Force | Out-Null }',
    '    if ($PSCommandPath -and ($PSCommandPath -ne $Destino) -and (Test-Path $PSCommandPath)) {',
    '      Copy-Item -Path $PSCommandPath -Destination $Destino -Force',
    '      Unblock-File -Path $Destino -ErrorAction SilentlyContinue',
    '    }',
    '  } catch {',
    '    Write-Host "Aviso: nao consegui usar a pasta fixa ($($_.Exception.Message)). Instalando do lugar atual."',
    '    $Destino = $PSCommandPath',
    '  }',
    '  $acao = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-WindowStyle Hidden -ExecutionPolicy Bypass -File `"$Destino`" -Loop"',
    '  $gatilho = New-ScheduledTaskTrigger -AtLogOn',
    '  # ExecutionTimeLimit ZERO e o mais importante aqui: o padrao do Windows',
    '  # MATA a tarefa depois de 3 dias rodando - o vigia roda pra sempre, entao',
    '  # sem isso ele morria em silencio 72h depois de cada login. Bateria: sem',
    '  # as duas flags, notebook na tomada solta nem iniciava o monitoramento.',
    '  $config = $null',
    '  try { $config = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -ExecutionTimeLimit (New-TimeSpan -Seconds 0) -MultipleInstances IgnoreNew } catch {}',
    '  try {',
    '    if ($config) { Register-ScheduledTask -TaskName $NomeTarefa -Action $acao -Trigger $gatilho -Settings $config -Force | Out-Null }',
    '    else { Register-ScheduledTask -TaskName $NomeTarefa -Action $acao -Trigger $gatilho -Force | Out-Null }',
    '    Escrever-Log "Instalado em $Destino - tarefa agendada \'$NomeTarefa\' criada (roda no proximo login desse usuario)."',
    '    Write-Host "Instalado! O NOCZenith vai rodar sozinho a partir do proximo login."',
    '    Write-Host "Ele agora roda de: $Destino"',
    '    Write-Host "Pode APAGAR o arquivo que voce baixou - nao precisa mais dele."',
    '  } catch {',
    '    Escrever-Log "FALHA ao registrar a tarefa agendada: $($_.Exception.Message)"',
    '    Write-Host "ERRO ao instalar a tarefa agendada: $($_.Exception.Message)"',
    '    Write-Host "Rode o PowerShell como Administrador e tente de novo."',
    '  }',
    '  # ---- blindagem contra reinicio (precisa de Administrador). A tarefa de',
    '  # login acima so dispara quando ALGUEM loga - depois de um reinicio, a',
    '  # maquina ficava na tela de login e o NOCZenith nunca voltava (foi',
    '  # exatamente o que derrubou o parque em ago/2026: os reinicios da',
    '  # manutencao mataram os vigias um a um). A tarefa de BOOT roda como',
    '  # SYSTEM, sobe junto com o Windows sem depender de login, e cede a vez',
    '  # pra instancia de login quando ela existir (ver UiEstaAtiva).',
    '  $ehAdmin = $false',
    '  try { $ehAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator) } catch {}',
    '  if ($ehAdmin) {',
    '    try {',
    '      $acaoBoot = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-WindowStyle Hidden -ExecutionPolicy Bypass -File `"$Destino`" -Loop -Servico"',
    '      $gatilhoBoot = New-ScheduledTaskTrigger -AtStartup',
    '      $principalBoot = New-ScheduledTaskPrincipal -UserId "SYSTEM" -LogonType ServiceAccount -RunLevel Highest',
    '      if ($config) { Register-ScheduledTask -TaskName ($NomeTarefa + "_Boot") -Action $acaoBoot -Trigger $gatilhoBoot -Principal $principalBoot -Settings $config -Force | Out-Null }',
    '      else { Register-ScheduledTask -TaskName ($NomeTarefa + "_Boot") -Action $acaoBoot -Trigger $gatilhoBoot -Principal $principalBoot -Force | Out-Null }',
    '      Escrever-Log "Tarefa de BOOT criada (SYSTEM) - o NOCZenith volta sozinho depois de qualquer reinicio, mesmo sem login."',
    '      Write-Host "Blindado contra reinicio: volta sozinho junto com o Windows, sem precisar de login."',
    '    } catch {',
    '      Escrever-Log "Nao consegui criar a tarefa de BOOT: $($_.Exception.Message)"',
    '      Write-Host "AVISO: nao consegui criar a tarefa de boot ($($_.Exception.Message)). Depois de um reinicio, o NOCZenith so volta quando alguem fizer login."',
    '    }',
    '  } else {',
    '    Write-Host ""',
    '    Write-Host "AVISO: instalado SEM Administrador. Depois de um reinicio, o NOCZenith so volta quando alguem fizer login nessa maquina."',
    '    Write-Host "Pra ele voltar sozinho apos reinicios, rode este mesmo comando num PowerShell aberto COMO ADMINISTRADOR."',
    '  }',
    '  Write-Host "Iniciando agora tambem, nessa sessao..."',
    '  Start-Process powershell.exe -ArgumentList "-WindowStyle Hidden -ExecutionPolicy Bypass -File `"$Destino`" -Loop"',
    '  Read-Host "Pronto! Pode fechar essa janela (aperte Enter)"',
    '}',
    '',
  ];

  return [...linhasComuns, ...(ehInterno ? linhasLoopInterno : linhasLoopOutros), ...linhasFinal].join('\n');
}

// comando de UMA LINHA pra colar no PowerShell da loja (botao "Copiar comando"
// na tela NOC Zenith). Baixa o script DIRETO pra pasta fixa
// (%LOCALAPPDATA%\NOCZenith) via Invoke-RestMethod - arquivo baixado assim NAO
// recebe o "Mark of the Web", entao o Controle de Aplicativo Inteligente do
// Windows 11 NAO bloqueia (que e o que trava o clique-direito num .ps1 baixado
// pelo navegador). O X-NOC-Token autentica na rota mesmo em reinstalacao (quando
// o computador ja tem segredo). Depois roda o arquivo (& $f), que se instala
// como tarefa agendada apontando pra essa mesma pasta fixa.
function montarComandoInstalacao({ codigo, posto, tipo, agentToken }) {
  const token = String(agentToken || '').replace(/[^a-f0-9]/gi, '');
  // encodeURIComponent NAO escapa o apostrofo ('), e a URL entra dentro de uma
  // string PowerShell de ASPAS SIMPLES ('...') abaixo - entao um codigo com
  // apostrofo (ex: "Domino's Carrinho...") fecharia a string ali e quebraria/
  // injetaria o comando. Trocar ' por %27 (que o servidor decodifica de volta)
  // mantem a URL correta e blindada dentro das aspas simples.
  const enc = (s) => encodeURIComponent(s).replace(/'/g, '%27');
  const url = `${APP_BASE_URL}/api/loja-status/${enc(codigo)}/computadores/${enc(posto)}/vigia.ps1?tipo=${enc(tipo)}`;
  // o script real (baixa direto pra pasta fixa - sem Mark of the Web, entao o
  // Controle de Aplicativo Inteligente nao bloqueia - e roda de la)
  const script = [
    "$ErrorActionPreference='Stop'",
    "$d=Join-Path $env:LOCALAPPDATA 'NOCZenith'",
    'New-Item -ItemType Directory -Path $d -Force|Out-Null',
    "$f=Join-Path $d 'NOCZenith.ps1'",
    `Invoke-RestMethod -Uri '${url}' -Headers @{'X-NOC-Token'='${token}'} -OutFile $f`,
    'Unblock-File -Path $f -ErrorAction SilentlyContinue',
    '& $f',
  ].join(';');
  // -EncodedCommand (Base64 de UTF-16LE): o comando vira uma string opaca, sem
  // nenhum $ ou aspas soltos. Sem isso, colar `powershell -Command "...$f..."`
  // DENTRO de outro PowerShell fazia o shell de fora expandir $d/$f (que nao
  // existem la) e o comando chegava com -OutFile/-Path/& vazios (erro real da
  // loja). Assim cola e roda igual no PowerShell, no CMD ou no Executar.
  const b64 = Buffer.from(script, 'utf16le').toString('base64');
  return `powershell -NoProfile -ExecutionPolicy Bypass -EncodedCommand ${b64}`;
}

module.exports = { montarScriptVigia, montarComandoInstalacao, VERSAO_VIGIA };
